### ISSUE TITLE
Internal Server Error While Trying to Login to Kubernetes Dashboard

### ISSUE THREAD

**Issue by bmxred** [kubernetes/dashboard#2867] opened 2018-02-27 16:46 UTC
##### Steps to reproduce
  1. Logged into Bluemix using CLI: bx login -a https://api.stage1.ng.bluemix.net
  2. Set context
      a. bx cs cluster-config <cluster_name_here>
  3. Copied and pasted the output from the previous command into my terminal and hit Enter.
  4. Verified environment variable set
      a.     env | grep kube
  5.  Copied default token and ran the following command
       a.     kubectl get secrets <token_name> -o yaml
  6. Base64-decoded API key:
      a.     echo <api_key> | base64 –-decode
  7. Copied the API key produced and started Kubernetes proxy as background process
      a.     kubectl proxy &
  8. Attempted to login to my K8S dashboard:
      a. Opened Firefox browser typed: localhost:8001/ui in address bar and hit Enter
      b. Clicked on the “Token” radial button
      c. Pasted the API key into the “Token” space and clicked on “Sign In”
  9. Received error

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.7.1
Commit: b44f7cc5fde4dbe2a884b1e32a2b363d8031e4ca
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by floreks** [comment] 2018-02-28 09:21
Duplicate of #2847.

**Closed by floreks** 2018-02-28 09:21 UTC
