### ISSUE TITLE
About heapster and metrics-server

### ISSUE THREAD

**Issue by ygqygq2** [kubernetes/dashboard#3270] opened 2018-09-26 02:00 UTC
Heapster is deprecated. Is metrics-server the substitute?

**Comment by jeefy** [comment] 2018-09-26 20:35
Metrics-Server will be the supported (hopefully) within two releases, before Heapster is fully deprecated and removed. 

Duplicate of #2986 
/assign
/close

**Closed by jeefy** 2018-09-26 20:35 UTC
