### ISSUE TITLE
Strange error after reinitializing cluster

### ISSUE THREAD

**Issue by shod4n** [kubernetes/dashboard#2238] opened 2017-08-04 18:50 UTC
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: @@BUILD_DASHBOARD_VERSION
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default".: "Unknown user \"system:serviceaccount:kube-system:default\"" (get replicationcontrollers)

```

**Comment by floreks** [comment] 2017-08-05 07:10
Duplicate of #2201, #2133.

**Closed by floreks** 2017-08-05 07:10 UTC
Labels: cluster-issue, duplicate
