### ISSUE TITLE
HTTP error while calling the API

### ISSUE THREAD

**Issue by urbaman** [kubernetes/dashboard#8843] opened 2024-03-28 21:56 UTC
### What happened?

Just installed chart v7.1.3, accessed the dashboard, it seems to have the old (2.7.0) look and feel, and keeps loading workloads forever:

![image](https://github.com/kubernetes/dashboard/assets/26753344/91ca8ad1-e063-4dbe-9baf-eea8970248f4)

Then it sends an HTTP error calling the API

![image](https://github.com/kubernetes/dashboard/assets/26753344/a8c991f1-3cb3-44c6-ab27-8a5e82ede99e)

### What did you expect to happen?

A working dashboard

### How can we reproduce it (as minimally and precisely as possible)?

helm upgrade -i kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -n kubernetes-dashboard
kubectl port-forward -n kubernetes-dashboard services/kubernetes-dashboard-kong-proxy 8443:443

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

Chart 7.1.3

### Kubernetes version

1.28.6

**Comment by floreks** [comment] 2024-04-05 14:51
Duplicate of https://github.com/kubernetes/dashboard/issues/8835

/close

**Closed by floreks** 2024-04-05 14:51 UTC
Labels: kind/bug
