### ISSUE TITLE
"Deploy a Containerized App - Upload" deploys into the default namespace if namespace metadata is not defined in the manifest

### ISSUE THREAD

**Issue by gatoruso** [kubernetes/dashboard#1864] opened 2017-04-19 21:39 UTC
#### Issue details

Regardless of the namespace currently selected using the dashboard's dropdown, an uploaded object is created in the `default` namespace, unless the object's manifest explicitly defines a different namespace in its metadata.

##### Environment
```
Dashboard version: 1.6.0
Kubernetes version: 1.4.9
Operating system: CentOS 7
```

##### Steps to reproduce
1. Ensure the Kubernetes cluster has at least one namespace other than default. For clusters with a `kube-system` namespace, this step is optional.
2. Open the dashboard.
3. Select any namespace other than `default`using the dashboard drop-down.
4. Click the "+ CREATE" button.
5. Select the "Upload a YAML or JSON file" method. 
6. Upload a file with this content:
```
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  ports:
  - port: 9999
```

Note: The Service object is used in this example, but the issue can be reproduced with another kind of Object, e.g., a Pod or Deployment.

##### Observed result
The `test-service` object is created in in the `default` namespace.

##### Expected result
The `test-service` object is created in the namespace selected using the dashboard drop-down.

##### Comments
I expect the dashboard's namespace drop-down to behave like `kubectl --namespace`, i.e., the selected namespace should apply to all verbs (including `create`) on namespaced API resources.

**Comment by maciaszczykm** [comment] 2017-04-20 08:10
Duplicate of #1374. Please track it from there.

**Closed by maciaszczykm** 2017-04-20 08:10 UTC
