### ISSUE TITLE
Toolbar hides when there's a popup opened in the app

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#303] opened 2016-01-27 15:52 UTC
@maciaszczykm Try opening image pull secret creation popup to reproduce. Maybe adding `z-index` can help?

**Comment by maciaszczykm** [comment] 2016-01-28 07:17
Okay, I'll check it.

**Comment by maciaszczykm** [comment] 2016-01-28 08:46
Okay, I got it. It was caused by Angular behavior, which sets `position: fixed` to `<body>` after clicking option picker. Setting `top: 0` on `kd-toolbar` fixes the issue. Created pull request #304, after it will be merged this issue can be closed.

**Comment by maciaszczykm** [comment] 2016-02-08 08:56
@bryk It's fixed now.

**Closed** 2016-02-08 09:41 UTC
