### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by zouyee** [kubernetes/dashboard#1854] opened 2017-04-18 03:03 UTC
#### Issue details
TypeError: Cannot read property 'length' of null when the value of replicaSet.pods.warnings is null
##### Environment

```
Dashboard version: 1.6.0
Kubernetes version: 1.5.3
Operating system: centos 7.2
Node.js version:
Go version: 
```

<img width="1133" alt="2017-04-18 11 01 55" src="https://cloud.githubusercontent.com/assets/5785605/25112874/7b5caad6-2426-11e7-870a-c4719f4eee87.png">

**Comment by bryk** [comment] 2017-04-18 07:18
@floreks @maciaszczykm is this compilation issue?

**Comment by floreks** [comment] 2017-04-18 07:34
I'll check.

**Comment by zouyee** [comment] 2017-04-18 08:04
maybe we need check the value of `replicaSet.pods.warnings`
```hasWarnings() {
      if (this.replicaSet.pods.warnings != null) {
       return this.replicaSet.pods.warnings.length > 0;
     }
     return true;
    }	
```

**Comment by maciaszczykm** [comment] 2017-04-18 08:10
@bryk No, we are missing null-check here.

**Comment by floreks** [comment] 2017-04-18 09:09
@bryk It seems for me like a compilation issue because it should never happen. In our backend me make sure that all arrays are initialized even if they are empty.

I have checked the code and IMO there is no way that warnings event array comes from backend as null. It is always initialized.

@zouyee could you tell me how did you come across this issue? I can't reproduce that unfortunately.

**Comment by zouyee** [comment] 2017-04-18 09:59
<img width="876" alt="2017-04-18 5 56 41" src="https://cloud.githubusercontent.com/assets/5785605/25125172/767ba140-2460-11e7-9699-dd6f355e7b18.png">
this issue cased by recreate event.
recreate deployment can not bring the replicaset and pods(kubernetes/kubernetes 44198)
recreate deployment w/ same name does not work(kubernetes/kubernetes 41760)

**Comment by floreks** [comment] 2017-04-18 10:55
hmm... we could introduce this check but this scenario is a definite kubernetes issue. Name and age are also wrong so object coming from kubernetes itself is already corrupted.

As you can reproduce it then maybe try to look at our backend and fix issue there because it should always return correctly initialized object. I have looked at the code and I'm not sure why it fails to initialize warnings correctly. Maybe there is an error thrown on backend side somewhere.

**Comment by zouyee** [comment] 2017-04-18 11:00
Under normal circumstances will not appear.

**Comment by floreks** [comment] 2017-06-27 09:53
Closing as this is kubernetes issue and should never happen under normal circumstances.

**Closed by floreks** 2017-06-27 09:53 UTC
Labels: kind/bug, priority/P3
