### ISSUE TITLE
recover from panic situation: - Failed to create heapster selector for resource "replicaset"

### ISSUE THREAD

**Issue by farcaller** [kubernetes/dashboard#2051] opened 2017-06-22 21:07 UTC
##### Steps to reproduce
 - Delete a replicaset from UI

##### Environment
```
Installation method: kubeadm + https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
Kubernetes version: 1.6.5
Dashboard version: v1.6.1
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
[restful] recover from panic situation: - Failed to create heapster selector for resource "replicaset". Error: getMyPodsFromCache: pods were not available in cache. Required for resource type: "replicaset"
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/asm_amd64.s:479
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/panic.go:458
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:160
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:240
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/replicaset/list.go:98
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/replicaset/list.go:82
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/replicaset/list.go:51
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:1141
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:377
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:267
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:21
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:179
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:19
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:140
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:19
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:103
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:19
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:204
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:19
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:269
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:120
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:1726
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:2022
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:287
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:2022
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:2202
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:1579
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/asm_amd64.s:2086

```

**Comment by floreks** [comment] 2017-06-23 07:33
Duplicate of #1916 as the cause is the same. Given step to reproduce does not work. The actual cause is different.

**Closed by floreks** 2017-06-23 07:33 UTC
Labels: duplicate
