### ISSUE TITLE
ConfigMaps Data editor crashes with: Uncaught TypeError: t.match is not a function

### ISSUE THREAD

**Issue by zerouid** [kubernetes/dashboard#4229] opened 2019-08-27 21:12 UTC
When I open a config map the data editor initially loads the the raw data strings (escaped JavaScript string), but immediately after this the content disappears and the exception below is logged to the console. After the crash the UI becomes unresponsive and I have to reload the page.

##### Environment
```
Installation method: https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta3/aio/deploy/recommended.yaml
Kubernetes version: v1.14.3
Dashboard version: v2.0.0-beta3
Operating system: linux/amd64
Node.js version ('node --version' output):
Go version ('go version' output):
Web browser: Google Chrome  v76.0.3809.132 / macOS
```

##### Steps to reproduce

1. Open Kubernetes dashboard and log in using Kubeconfig or Token.
2. Go to any existing ConfigMap that contains data. 

##### Observed result
The raw data string appears in the editor and quickly disappears and the UI remains unresponsive. In the Developer console the following error appears:
```
Uncaught TypeError: t.match is not a function
    at u.$detectNewLine (main.a265afe24a905d94a59f.js:1)
    at u.insert (main.a265afe24a905d94a59f.js:1)
    at u.setValue (main.a265afe24a905d94a59f.js:1)
    at v.setValue (main.a265afe24a905d94a59f.js:1)
    at t.setText (main.a265afe24a905d94a59f.js:1)
    at t.set [as text] (main.a265afe24a905d94a59f.js:1)
    at Yo (main.a265afe24a905d94a59f.js:1)
    at main.a265afe24a905d94a59f.js:1
    at main.a265afe24a905d94a59f.js:1
    at Us (main.a265afe24a905d94a59f.js:1)
```

##### Expected result
To be able to view and edit ConfigMap data.

##### Comments
I don't have a development environment setup locally, but I can assist if any further information is neaded.
Thanks!

**Comment by floreks** [comment] 2019-08-27 22:03
Duplicate of #4092 
/close

**Closed as completed by floreks** 2019-08-27 22:03 UTC
Labels: kind/bug
