### ISSUE TITLE
Cannot view crontab jobs in Kubernetes Dashboard

### ISSUE THREAD

**Issue by oscarbatori** [kubernetes/dashboard#2179] opened 2017-07-25 13:35 UTC
##### Environment
```
Dashboard version: packaged with Minikube 0.20.0
Kubernetes version: 1.64
Operating system: OSX
Node.js version: v4.3.2
Go version: 1.8.1
```

##### Steps to reproduce
```
$ curl https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/cronjob.yaml > cronjob.yaml
$ kubectl create -f cronjob.yaml
cronjob "hello" created
```

##### Observed result
```
$ kubectl get cronjobs
NAME         SCHEDULE      SUSPEND   ACTIVE    LAST-SCHEDULE
cron-hello   */1 * * * *   False     0         Tue, 25 Jul 2017 09:31:00 -0400
```

##### Expected result
N/A

##### Comments
We would like to be able to view a list of scheduled `CronJob` in the GUI. Currently we can see only historical execution in the GUI.

cc: @avshah

**Comment by maciaszczykm** [comment] 2017-07-25 13:38
Duplicate of https://github.com/kubernetes/dashboard/issues/1562.

**Closed by maciaszczykm** 2017-07-25 13:38 UTC

**Comment by oscarbatori** [comment] 2017-07-25 13:39
@maciaszczykm super, thanks!
