### ISSUE TITLE
No possibility of deploying applications when "Run as privileged" is enabled

### ISSUE THREAD

**Issue by kwodzynski** [kubernetes/dashboard#622] opened 2016-04-07 07:11 UTC
#### Issue details
No possibility of deploying applications when "Run as privileged" is enabled

##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1
Kubernetes version: v1.3.0-alpha.0.604+b494cbc0c17dd7
Operating system: Ubuntu 15.10 4.2.0-34-generic
Node.js version: v0.10.40
Go version: go1.5.1
```

##### Steps to reproduce
I try deploy app by a form
I fill in all of required fields and check checkbox "Run as privileged"

##### Observed result
App is not deploying and in browser's console I see error:
```
Error deploying application: Object {data: "ReplicationController "test" is invalid: spec.temp…
text.privileged: Forbidden: disallowed by policy↵", status: 500, config: Object, statusText: "Internal 
Server Error"}config: Objectdata: Objectheaders: Objectmethod: "POST"paramSerializer: 
ngParamSerializer(params)transformRequest: Array[1]transformResponse: Array[1]url: 
"api/v1/appdeployments"__proto__: Objectdata: "ReplicationController "test" is invalid: 
spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by 
policy↵"headers: (name)arguments: (...)caller: (...)length: 1name: ""prototype: Object__proto__: ()
<function scope>status: 500statusText: "Internal Server Error"__proto__: Object
```

##### Expected result
I should have the possibility deploying app as privileged

**Comment by cheld** [comment] 2016-04-07 07:36
Have you tried the same action using CLI?

hmm..unfortunately this option is not available with "kubectl run". You must use kubectl create -f...

**Comment by floreks** [comment] 2016-04-07 07:39
This is actually issue with error handling. API server responds with error `Forbidden: disallowed by 
policy`. This means probably that kubelet or api-server don't have privileges to create app with administrative privileges.

[This](http://stackoverflow.com/questions/34776060/kubernetes-privileged-container-in-linux-docker-multinode-cluster) and https://github.com/kubernetes/kubernetes/issues/391 should cover how to setup cluster to allow creation of such apps.

**Comment by floreks** [comment] 2016-04-07 09:05
For local tests just run `sudo PATH=$PATH ALLOW_PRIVILEGED=true ./hack/local-up-cluster.sh`. This will allow creation of privileged apps.

**Comment by cheld** [comment] 2016-04-08 11:08
I think just the normal error dialog should show the server message. Good enough. So, I would suggest to say this is duplicate of #592

**Comment by cheld** [comment] 2016-04-08 11:12
thanks for investigation.

@maciaszczykm how can I mark bugs as duplicate?

**Comment by maciaszczykm** [comment] 2016-04-08 11:28
@cheld There is a __duplicate__ label, just assign it.

**Closed** 2016-04-08 11:29 UTC
Labels: area/validation, duplicate, kind/bug, priority/P2
