### ISSUE TITLE
gulp serve watch fails

### ISSUE THREAD

**Issue by batikanu** [kubernetes/dashboard#143] opened 2015-12-08 17:05 UTC
gulp serve watch fails with the error below:

```
[17:51:24] Starting 'backend'...
[17:51:24] Finished 'index' after 70 ms
[17:51:24] Starting 'watch'...
[17:51:24] Finished 'watch' after 76 ms
# k8s.io/kubernetes/pkg/api/errors
Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/errors/errors.go:171: undefined: validation.ErrorList
# k8s.io/kubernetes/pkg/util
Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/throttle.go:61: t.limiter.Capacity undefined (type *ratelimit.Bucket has no field or method Capacity)
Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/throttle.go:62: t.limiter.Available undefined (type *ratelimit.Bucket has no field or method Available)
godep: go exit status 2
[17:51:24] 'backend' errored after 258 ms
[17:51:24] Error: Go command error, code: 1
    at Error (native)
    at ChildProcess.<anonymous> (gocommand.js:119:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

 @bryk @maciaszczykm @floreks @zreigz  is there any missing Godep which isn't checked in?

**Comment by bryk** [comment] 2015-12-09 08:30
Hmm... This works on Travis which runs clean build every time. Which go version do you use?

Can any of you reproduce this? 

CC @taimir

**Comment by maciaszczykm** [comment] 2015-12-09 08:34
Works for me.

**Comment by cheld** [comment] 2015-12-09 09:15
I checked out dashboard twice. One version has some changes and is not fully up-to-date. In this version 'gulp serve:prod' works, but 'gulp serve' does not work. This could explain why it was not detected by Travis. Of course it is also possible that my workspace is messed up.

The other version I just checked out a clean version from master. In this case both work fine.

My go version is 1.4. However, according to my documentation it should be 1.5... :o))

I think we can close the issue. If it happens again we should investigate

**Comment by taimir** [comment] 2015-12-09 09:34
I do not see any problem on my machine at home so far. @batikanu If the problem persists I can investigate it tomorrow.

**Comment by cheld** [comment] 2015-12-10 07:45
switching from go version 1.4 to 1.5 helped, but I still don't get it, because I could build a clean checkout of dashboard with version 1.4....

**Comment by bryk** [comment] 2015-12-10 08:47
We've updated Kubernetes Code go dependency, that's why it stopped working.

How about we check for go version in our build scripts?

**Comment by batikanu** [comment] 2015-12-10 08:51
After upgrading go from 1.4 to 1.5 without any extra attempt it works.

**Comment by bryk** [comment] 2015-12-10 08:52
@batikanu Can you implement check for go version in our build pipeline? To prevent this from happening in the future.

**Comment by batikanu** [comment] 2015-12-10 08:59
Ok I will modify it accordingly.

**Comment by bryk** [comment] 2015-12-11 13:17
This is fixed.

**Closed by bryk** 2015-12-11 13:17 UTC
