### ISSUE TITLE
Docker image error trying to execute dashboard locally 

### ISSUE THREAD

**Issue by Kh40sz3r0** [kubernetes/dashboard#2229] opened 2017-08-03 01:08 UTC
##### Environment

```
Dashboard version: Code in the master branch
Kubernetes version: 1.7.0
Operating system: macOS 10.12.6
Node.js version: v6.9.2
Go version: go1.8.3 darwin/amd64
Docker:
  Client
    Version:      1.12.6
    API version:  1.24
    Go version:   go1.6.4
    Git commit:   78d1802
    Built:        Wed Jan 11 00:23:16 2017
    OS/Arch:      darwin/amd64
  Server
    Version:      1.12.6
    API version:  1.24
    Go version:   go1.6.4
    Git commit:   78d1802
    Built:        Wed Jan 11 00:23:16 2017
    OS/Arch:      linux/amd64
```

##### Steps to reproduce
I execute the command `gulp local-up-cluster` which keep responding 
`[20:04:02] Waiting for a Heapster ...
[20:04:12] Waiting for a Kubernetes cluster at http://localhost:8080... 
[20:04:12] Waiting for a Heapster ...
`

Executing `docker ps -a` i am getting the next information

`5e9ed0c87f99        gcr.io/google_containers/heapster:v1.2.0          "/heapster -port 8..."   6 seconds ago       Exited (255) 4 seconds ago                            modest_goldwasser
26751a2a1f1d        gcr.io/google_containers/hyperkube-amd64:v1.7.0   "/nsenter --target..."   7 seconds ago       Exited (1) 5 seconds ago                              vibrant_kilby`

Executing `docker logs 26751a2a1f1d` i am getting the next output

`nsenter: failed to execute ./hyperkube: No such file or directory`

I have been trying different hyperkube version without success

##### Observed result
The containers are not being correctly executed

##### Expected result
I would like to know how to resolve the issue

##### Comments
No other comments for now

**Comment by maciaszczykm** [comment] 2017-08-03 06:27
@Kh40sz3r0 Have you tried `minikube` or `kubeadm` instead of `gulp local-up-cluster`, which is outdated (we will migrate it sooner or later, because of `hyperkube`)?

**Comment by floreks** [comment] 2017-08-03 06:54
`local-up-cluster` does not work on macOS. You have to use other method to provision the cluster.

**Comment by floreks** [comment] 2017-08-03 06:55
Duplicate of #1987. Closing.

**Closed by floreks** 2017-08-03 06:55 UTC
