### ISSUE TITLE
CPU utilization graph is flickering on large screens

### ISSUE THREAD

**Issue by ysaakpr** [kubernetes/dashboard#5102] opened 2020-05-03 12:50 UTC
Using the latest v2 release.
The CPU graph in all pages is flickering while opened in MacBook pro 16 inches. If I reduce the window size a bit the flickering stops. Attached a screen recording of. the same. Started this last beta release onwards.

**Comment by floreks** [comment] 2020-05-03 18:13
Duplicate of https://github.com/kubernetes/dashboard/issues/5050

/close

**Closed** 2020-05-03 18:13 UTC
Labels: kind/bug
