### ISSUE TITLE
Shell in safari has height of 8 

### ISSUE THREAD

**Issue by outcoldman** [kubernetes/dashboard#2183] opened 2017-07-26 04:51 UTC
```
Dashboard version: 1.6.2
```

In chrome everything works as expected - taking whole space, but in safari it takes only 8 lines for some reason. See below.

<img width="1607" alt="screen shot 2017-07-25 at 9 50 18 pm" src="https://user-images.githubusercontent.com/597158/28604947-4658af2e-7183-11e7-926a-b0e1d9945989.png">

cc @IanLewis

**Comment by maciaszczykm** [comment] 2017-07-26 07:41
I can confirm it.

**Comment by cnwalker** [comment] 2017-07-27 08:46
I'm not seeing this <img width="1424" alt="screen shot 2017-07-27 at 1 43 07 am" src="https://user-images.githubusercontent.com/8570077/28661833-ebe7ff8c-726c-11e7-8a13-edd983a131a5.png">

Safari version 10.1.2, OSX version 10.12.6

**Comment by discostur** [comment] 2017-07-27 15:24
+1

**Comment by maciaszczykm** [comment] 2017-08-04 07:05
Unfortunately, I couldn't find a clean way to do this now. Safari ignores `height: 100%` for iframe which is added by https://github.com/lenartj/hterm. I think it should be fixed upstream or we should consider changing library if we will be able to find something which is working everywhere. I am linking @lenartj, because he is author of https://github.com/lenartj/hterm.

@lenartj I tried to set:  
``` scss
.kd-shell-term {
  overflow: hidden;
  width: 100%;

  iframe {
    min-height: 100%;
  }
}
```

But then iframe is bigger than `kd-shell-term` div.

**Comment by maciaszczykm** [comment] 2017-09-28 12:01
We will track from #2420.

**Closed by maciaszczykm** 2017-09-28 12:01 UTC
Labels: kind/bug, priority/P2
