### ISSUE TITLE
Kubernetes Dashboard ignores numer of Items after reordering

### ISSUE THREAD

**Issue by WolfyLPDC** [kubernetes/dashboard#3497] opened 2019-01-10 13:57 UTC
##### Environment

```
Installation method: Official YAML
Kubernetes version: 1.13.1
Dashboard version: 1.10.1
Operating system: Ubuntu 16.04
Browser: Firefox 64.0 (64bit)
```

##### Steps to reproduce
(I did this exactly with 50 nodes active)
Go to `Settings` and select a custom number of `Items per page`. After that, go to any view (as for example, `Pods`) and order the elements by something, like for example `Age`. 

##### Observed result

There are listed only ten elements, as the default value of `Items per page`. Also, there is no possibility to select the next elements. 

##### Expected result

To be able to see `Itemps per page` elements per page.

##### Comments

I will personally take a look to it because it seems to be something that developers forgot.

*Edit:*

#### Pictures
10/50 pods are shown, everything is ok
![kubernetes-dashboard-10-pods](https://user-images.githubusercontent.com/16905453/51018220-19d21280-1577-11e9-9d27-d6e8c6bb1a2f.png)
I select in `Settings` that I want to see 50 items per page
![kubernetes-dashboard-50-items-per-page](https://user-images.githubusercontent.com/16905453/51018226-2191b700-1577-11e9-9b1c-9231c2c6aad2.png)
50/50 pods are shown, everything is ok
![kubernetes-dashboard-50-pods](https://user-images.githubusercontent.com/16905453/51018229-23f41100-1577-11e9-8094-b89d0e0e03ab.png)
After sorting: 10/50 pods are shown. There is no possibility to see more elements.
![kubernetes-dashboard-bug](https://user-images.githubusercontent.com/16905453/51018233-25bdd480-1577-11e9-973c-8c21af810ac4.png)

**Comment by floreks** [comment] 2019-01-10 14:05
I actually can not reproduce that. Tested right now on `v1.10.1` and everything works fine. After selecting 15 items, I can use sorting, filtering and change list pages as expected.

**Comment by maciaszczykm** [comment] 2019-01-10 14:07
Perhaps that has something to do with Kubernetes v1.13 not being compatible with our release.

**Comment by floreks** [comment] 2019-01-10 14:09
I have tested it on k8s `v1.13.1` so that it not it. Maybe it's an issue with privileges to read settings config map.

**Comment by WolfyLPDC** [comment] 2019-01-11 07:06
Update with pictures. Perhaps the problem is that, as there are 50/50 pods, navigation bar is not shown and, after reducing elements (which should not reduce  `Items per page`), the bar is not drawn again.

**Comment by floreks** [comment] 2019-01-11 08:36
@WolfyLPDC I am wondering if you really using `v1.10.1` version. I have checked exactly the steps you have described and everything is fine.

1. Default items per page
![zrzut ekranu z 2019-01-11 09-32-01](https://user-images.githubusercontent.com/2285385/51022284-20b35200-1584-11e9-94b0-cf6ae58f1c53.png)

2. Changing to 50
![zrzut ekranu z 2019-01-11 09-32-10](https://user-images.githubusercontent.com/2285385/51022291-227d1580-1584-11e9-9d11-9157bcf48885.png)

3. Going to pods, everything looks fine
![zrzut ekranu z 2019-01-11 09-32-25](https://user-images.githubusercontent.com/2285385/51022323-3759a900-1584-11e9-8548-60d78fb67158.png)

4. Changed sorting to by status
![zrzut ekranu z 2019-01-11 09-32-51](https://user-images.githubusercontent.com/2285385/51022353-480a1f00-1584-11e9-9621-dc90df046d10.png)

5. Pager still visible
![zrzut ekranu z 2019-01-11 09-34-04](https://user-images.githubusercontent.com/2285385/51022369-4e989680-1584-11e9-82cd-471e79394eb3.png)

**Comment by WolfyLPDC** [comment] 2019-01-11 10:22
I'm using 1.10.1. Take a look to the `About` view:

*About*
**Dashboard**
*General-purpose web UI for Kubernetes clusters*
Dashboard Version: v1.10.1
Git Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0 

Have you do it in Firefox? It is strange. I do not think it is a bad installation.

**Comment by floreks** [comment] 2019-01-11 12:03
I have tried on Firefox also and cannot reproduce it also. It might only appear when dealing with real cluster under load, not my small local kubeadm cluster.

**Comment by WolfyLPDC** [comment] 2019-01-11 13:08
I'm using a test cluster in VirtualBox and there is no real load, so I do not think that it is the problem. I do not know what other information add here.

**Comment by floreks** [comment] 2019-01-11 13:11
Can you try out head image and see if it still occurs? 

```
$ kubectl apply -f https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended/kubernetes-dashboard-head.yaml
```
Access path should be:
```
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard-head:/proxy/
```

This is just to test this one thing. This image is just a preview of dashboard v2. Many things are not working correctly yet.

**Comment by WolfyLPDC** [comment] 2019-01-11 13:39
I'm going to be busy this weekend. Say me what should I try and Monday I'll send all the screenshots requested.

**Comment by WolfyLPDC** [comment] 2019-01-14 11:41
@floreks I have tried the image but still does not work. Do you have an update?

**Comment by floreks** [comment] 2019-01-14 14:49
@WolfyLPDC Ye, I do have an update :slightly_smiling_face: Apparently `client-go` has introduced some breaking changes to the way in-cluster config works now and we have to refactor our code, to make it work again. I'll try to do it somewhere this week.

**Comment by WolfyLPDC** [comment] 2019-01-14 15:09
@floreks 
Ok. Tag me if you want me to test it.

**Comment by floreks** [comment] 2019-01-24 10:12
@WolfyLPDC could you follow instruction from my previous comment (https://github.com/kubernetes/dashboard/issues/3497#issuecomment-453512372) and retest? Head image should be fixed now.

**Comment by WolfyLPDC** [comment] 2019-01-24 11:43
@floreks Tested! It seems to work fine. Good job.

**Comment by floreks** [comment] 2019-01-24 11:47
Great. It will be available in the next release. Thanks for testing.

/close

**Closed by floreks** 2019-01-24 11:47 UTC
Labels: kind/bug
