### ISSUE TITLE
Fix namespace selector on detail pages

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#789] opened 2016-06-01 11:42 UTC
@taimir correctly notices flaws in current implementation:

> When I'm on the detail page of, say, a pod in namespapce default the url is like /pod/default/pod-whatever?namespace=default. Now suppose I switch the namespace from the toolbar to namespace my-namepsace. The URL becomes /pod/default/pod-whatever?namespace=my-namespace ... And now it is totally unclear to me what the user might think. Because he just switched to a different namespace, but still sees the pod from the previous one. I'd like to avoid the discrepancy in the URL between the two namespace params.
> 
> One quick solution I can think of is to simply not allow a namespace change on the details view of any resource? Because right now changing the namespace on a details view just does nothing for me.

Other solution would be to redirect to list page on namespace change on details view.

**Comment by taimir** [comment] 2016-06-01 11:44
(nod) yes, your suggestion sounds reasonable to me. Opinions from the others? @floreks @maciaszczykm

**Comment by maciaszczykm** [comment] 2016-06-01 12:20
> The URL becomes /pod/default/pod-whatever?namespace=my-namespace ... And now it is totally unclear to me what the user might think. Because he just switched to a different namespace, but still sees the pod from the previous one.

If my understanding is correct, then user shouldn't see **the same** pod here. Pod with same name, but from different namespace should be displayed IMO. Am I wrong?

> Other solution would be to redirect to list page on namespace change on details view.

I agree, it seems the most user-friendly behavior, but disabling namespace change on non-list views is also good solution.

**Comment by taimir** [comment] 2016-06-01 12:28
>If my understanding is correct, then user shouldn't see the same pod here. Pod with same name, but from different namespace should be displayed IMO. Am I wrong?

@maciaszczykm so the current behavior will be fixed, as I discussed with @bryk. Right now it still displays the same pod. Displaying a pod with the same name but from a different namespace seems unlikely though - because of the pod naming scheme in k8s, there is not much chance to get two pods in two different namespaces with the same name (since pods are mostly named after their RC with a randomized suffix).

**Comment by maciaszczykm** [comment] 2016-06-01 12:32
> @maciaszczykm so the current behavior will be fixed, as I discussed with @bryk. Right now it still displays the same pod. Displaying a pod with the same name but from a different namespace seems unlikely though - because of the pod naming scheme in k8s, there is not much chance to get two pods in two different namespaces with the same name (since pods are mostly named after their RC with a randomized suffix).

@taimir Yeah, that's why I'd pick between two proposed solutions.

**Comment by taimir** [comment] 2016-06-01 12:36
The more I think about it, the more I like the "redirect to list view" idea. Just having the currently selected namespace in the top right corner is a helpful indication on its own, so I think I'd prefer to not leave it out :)

**Comment by bryk** [comment] 2016-06-01 14:33
Yeah, I treat namespaces like "projects" and it is good to see what project you're in. The thing that causes problems with urls like `/pod/default/pod-whatever?namespace=my-namespace` is that we can select _no namespace_ meaning that on list pages we see stuff from all namespaces. That's why we need a param for namespace (aka "project") and namespace of an object we look at the moment.
If the user just clicks around the application, the params will stay in sync. If the user hacks the URL we can do whatever we want => hacked URLs are not our support target.

**Comment by rf232** [comment] 2016-11-18 09:49
duplicate of #816

**Closed by rf232** 2016-11-18 09:49 UTC
Labels: area/ux, kind/enhancement, priority/P1
