### ISSUE TITLE
Dashboard reported Gateway Time-out (504) on logs page

### ISSUE THREAD

**Issue by ffelicissimo** [kubernetes/dashboard#1816] opened 2017-04-04 17:11 UTC
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Gateway Time-out (504):
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>awselb/2.0</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by maciaszczykm** [comment] 2017-04-05 09:30
Please provide us more details before reopening.

**Comment by ffelicissimo** [comment] 2017-04-05 13:25
Passing more information about my environment I'm using "Rancher" to provision the environment on Amazon the Rancher version I'm using is 1.4.3.

Dashboard version: v1.5.0
Kubernetes version: v1.5.2
Operating system: Ubuntu 16.0.4
Node.js version: 
Go version:

**Comment by maciaszczykm** [comment] 2017-04-05 13:32
@ffelicissimo What about steps to reproduce? You cannot access Dashboard at all? We need to know more, because it's most probably configuration issue.

**Comment by ffelicissimo** [comment] 2017-04-05 14:28
I can usually access the dashboard the reported error appears when I select to see the "POD" log.

**Comment by maciaszczykm** [comment] 2017-04-06 08:24
@ffelicissimo Can you display lods of this pod from kubectl? Can you provide pod spec?

**Comment by ffelicissimo** [comment] 2017-04-06 12:47
@maciaszczykm What would "lods" pods be?

Through "kubectl" I can not see the logs and no access to the pod console

**Comment by maciaszczykm** [comment] 2017-04-06 13:04
> @maciaszczykm What would "lods" pods be?

`lods = logs`

> Through "kubectl" I can not see the logs and no access to the pod console

What is an output of `kubectl get logs ...`?

**Comment by floreks** [comment] 2017-05-09 07:55
I can see that you are accessing dashboard through AWS Load Balancer. Since you see this message after you try to access pod logs then I think that backend crashes. Since Load Balancer can't ping it then it displays this page with timeout error.

Probably the main cause is out of memory error. We are aware of that issue and one possible solution is to increase memory limits and requests for dashboard app. We will be tracking it from #1828 so I'm closing this one.

**Closed by floreks** 2017-05-09 07:55 UTC
Labels: missing-details
