### ISSUE TITLE
Unable to access kubernetes dashboard in google chrome

### ISSUE THREAD

**Issue by vr2388** [kubernetes/dashboard#7735] opened 2023-05-16 10:16 UTC
### What happened?

Hi,
 I am able to open the Kubernetes dashboard in Firefox but not in Chrome.
In Chrome it shows the below error

**Error message**
Your connection is not private
Attackers might be trying to steal your information from (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_INVALID
To get Chrome’s highest level of security, turn on enhanced protection
normally uses encryption to protect your information. When Chrome tried to connect to this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit at the moment because the website sent scrambled credentials that Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

### What did you expect to happen?

Kubernetes dashboard should open in google chrome

### How can we reproduce it (as minimally and precisely as possible)?

Install Kubernetes dashboard and open it in google chrome, you will get below error

Your connection is not private
Attackers might be trying to steal your information from (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_INVALID
To get Chrome’s highest level of security, turn on enhanced protection
normally uses encryption to protect your information. When Chrome tried to connect to this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit at the moment because the website sent scrambled credentials that Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

2.1.0

### Kubernetes version

v1.19.8-34+811e9feeade1d3   and above

**Comment by floreks** [comment] 2023-05-16 10:19
Duplicate of https://github.com/kubernetes/dashboard/issues/3804

/close

**Closed by floreks** 2023-05-16 10:19 UTC
Labels: kind/bug
