### ISSUE TITLE
v1.6.2 don't show heapster graph

### ISSUE THREAD

**Issue by Bobi-zhou** [kubernetes/dashboard#2185] opened 2017-07-26 11:43 UTC
dashboard don't show heapster but 1.6.1 can,why?

**Comment by floreks** [comment] 2017-07-26 11:44
Duplicate of #2180. I have described workaround in there and if you deploy dashboard with command from our readme it will work. 

It is already fixed and we will push `1.6.3` version in a few days.

**Closed** 2017-07-26 11:44 UTC
Labels: duplicate
