### ISSUE TITLE
Create sample User MD missing information

### ISSUE THREAD

**Issue by iwan933** [kubernetes/dashboard#7112] opened 2022-05-17 19:52 UTC
### What happened?

Since Kubernetes 1.24 no bearer token is created by default (https://github.com/kubernetes/kubernetes/pull/108309) - as such docs at

https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

will not work.

### What did you expect to happen?

Docs mention the new feature gate

### How can we reproduce it (as minimally and precisely as possible)?

Initialize kubernetes cluster v1.24 with kubeadm, default user will not have a autogenerated bearer token.

### Kubernetes Dashboard version

latest

### Kubernetes version

1.24

**Comment by huangyan20** [comment] 2022-05-18 04:50
Yes, I have the same problem,
Kubernetes version: 1.24

**Comment by floreks** [comment] 2022-05-18 05:32
Duplicate of quite a few issues. Search already closed ones.

/duplicate
/close

**Closed** 2022-05-18 05:32 UTC
Labels: kind/bug
