### ISSUE TITLE
Dashboard reported Unknown Server Error (503)

### ISSUE THREAD

**Issue by spielerorasio** [kubernetes/dashboard#1575] opened 2017-01-17 13:42 UTC
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Unknown Server Error (503):
```
Error: 'EOF'
Trying to reach: 'http://100.96.22.52:9090/api/v1/pod/mc-qa-nightly/console-deployment-1206982207-1i6c1/log'
```

**Comment by IanLewis** [comment] 2017-01-20 04:47
Duplicate of #1555

**Closed by IanLewis** 2017-01-20 04:47 UTC
Labels: kind/duplicate
