### ISSUE TITLE
Image points to wrong binary type in yaml

### ISSUE THREAD

**Issue by ansilh** [kubernetes/dashboard#3449] opened 2018-12-20 19:52 UTC
##### Environment
Installed k8s 12.0.1 from scratch on Ubuntu 16.04 in VirtualBox
Followed README.md 

##### Steps to reproduce
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

```

##### Observed result
```
kubectl logs kubernetes-dashboard-547674fff5-h4wh6 -n kube-system
standard_init_linux.go:190: exec user process caused "exec format error"
```
```
kubernetes-dashboard.yaml 
...
image: k8s.gcr.io/kubernetes-dashboard-arm:v1.10.1 <-- Default yamls's image supposed to be amd64 
...
```
##### Expected result

Its supposed to be like ;
```
kubernetes-dashboard-arm.yaml -->image: k8s.gcr.io/kubernetes-dashboard-arm:v1.10.1
kubernetes-dashboard.yaml --> image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
```

**Comment by RothAndrew** [comment] 2018-12-20 19:54
Duplicate of #3447

**Comment by maciaszczykm** [comment] 2018-12-21 10:00
Fixed.

/close

**Closed by maciaszczykm** 2018-12-21 10:00 UTC
