### ISSUE TITLE
Kubernetes-dashboard plugin is not working

### ISSUE THREAD

**Issue by harisudarsan1** [kubernetes/dashboard#8674] opened 2024-02-08 12:43 UTC
### What happened?

The existing builder in the plugin-base branch is not working. I tried modifying it and tried to build the plugin but it shows errors like app.ngFactory doesn't exist seems like aot compilation is not taking place. 

Is there any working plugins to refer?

### What did you expect to happen?

The plugin should be compiled into a single javascript file for loading the plugin into the dashboard

### How can we reproduce it (as minimally and precisely as possible)?

switch to the plugin-base branch and try to build the plugin 

### What browsers are you seeing the problem on?

Firefox

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

v1.29.1

### Dev environment

Node:20.11 
kubernetes setup with minikube(1.32.0)
go 1.21.6

**Comment by harisudarsan1** [comment] 2024-02-20 13:38
checkout these https://github.com/harisudarsan1/kubearmor-plugin and https://github.com/vuesomedev/angular2-aot-cli-webpack-plugin for reference. We achieve the same build with a custom webpack config for AOT compilation as mentioned in above references. We can also able to write a custom builder for AOT compilation and modifying the webpack configuration for the build. The custom webpack config can be referenced from the kubernetes custom builder.

**Comment by maciaszczykm** [comment] 2024-02-23 15:01
Duplicate of https://github.com/kubernetes/dashboard/issues/8713.

**Closed by maciaszczykm** 2024-02-23 15:01 UTC
Labels: kind/bug
