### ISSUE TITLE
kube-dashboard and kubeadm

### ISSUE THREAD

**Issue by jeroenjacobs1205** [kubernetes/dashboard#1802] opened 2017-03-31 09:53 UTC
I have setup a one-node Kubernetes cluster using kubeadm. This deployed a Kubernetes 1.6 cluster, and this cluster seems to be working.

Then I installed kube-dashboard:

```
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
deployment "kubernetes-dashboard" created

```
Then I run kubectl proxy:

```
# kubectl proxy
Starting to serve on 127.0.0.1:8001
```

When I point my browser on the machine to http://127.0.0.1:8001/ui/, I see parts of the UI, but I'm getting authentication errors everywhere:

`User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)`

What do I need to do to get a working dashboard?

**Comment by jeroenjacobs1205** [comment] 2017-03-31 10:10
I tried deleting the secret, and it got recreated. However, no improvement.

I'm able to access http://localhost:8001 just fine. The error only pops up when I add the /ui/ part.

**Comment by floreks** [comment] 2017-03-31 10:25
Looks like a duplicate of #1800

**Closed** 2017-03-31 10:25 UTC
