### ISSUE TITLE
Dashboard reported Forbidden 

### ISSUE THREAD

**Issue by ArmorHerO** [kubernetes/dashboard#1824] opened 2017-04-06 10:54 UTC
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)
```

**Comment by floreks** [comment] 2017-04-06 10:59
Duplicate of #1803.

**Closed by floreks** 2017-04-06 10:59 UTC

**Comment by ArmorHerO** [comment] 2017-04-06 11:12
thanks,  I slove it， but I want know "why", it's a bug or what

**Comment by maciaszczykm** [comment] 2017-04-06 11:14
@ArmorHerO Check #1803. We have to describe it, because a lot of people have similar problem.
