### ISSUE TITLE
Secrets visible in UI when referenced via environment variable

### ISSUE THREAD

**Issue by pfremm** [kubernetes/dashboard#2018] opened 2017-06-06 18:47 UTC
##### Environment

```
Dashboard version: 1.6.1
Kubernetes version: 1.6.2
Operating system: Centos 7.3

```

##### Steps to reproduce

Reference secrets via environment variables and view a pod definition in the dashboard
##### Observed result

Secrets referenced via environment variable will be visible within the UI.
##### Expected result
Secrets should be hidden and not shown in the UI

##### Comments
It appears this broke since 1.6.

**Comment by maciaszczykm** [comment] 2017-06-08 10:12
Duplicate of https://github.com/kubernetes/dashboard/issues/1993.

**Closed by maciaszczykm** 2017-06-08 10:12 UTC
Labels: duplicate

**Comment by cheld** [comment] 2017-06-09 04:21
@maciaszczykm sure it is a duplicate?

**Comment by maciaszczykm** [comment] 2017-06-09 05:12
@cheld Yes, few weeks ago I have added extended handling for environment variables, able to read values from secrets. So now, if pod has environment variable refering secret and user has no right to see secrets, whole page will not be displayed.
