### ISSUE TITLE
I was able to create a RC with an already existing name

### ISSUE THREAD

**Issue by olekzabl** [kubernetes/dashboard#445] opened 2016-02-25 14:59 UTC
Name: heapster-v11
Time: 2/25, ca. 14:45 UTC
There was no warning about name clash.
(See the left part of the screenshot).

![screenshot from 2016-02-25 15 58 29](https://cloud.githubusercontent.com/assets/17475944/13323224/a98bdb3a-dbd8-11e5-8df4-2806f2e1577d.png)

**Comment by floreks** [comment] 2016-02-25 15:00
Are they located in the same namespace or in different namespaces?

**Comment by olekzabl** [comment] 2016-02-25 16:11
No, in different namespaces. Thanks and sorry for a false bug.

**Comment by cheld** [comment] 2016-02-25 17:32
Well, it is still a bug. However it is not the creation, but not indicating namespace when displaying.

**Comment by cheld** [comment] 2016-02-26 07:16
Showing namespaces is a duplicate

**Comment by bryk** [comment] 2016-03-01 09:18
Correct, this is a real issue. Duplicate of https://github.com/kubernetes/dashboard/issues/348

**Closed by bryk** 2016-03-01 09:18 UTC
