### ISSUE TITLE
StatefulSet volumeClaim deleted with pod deletion

### ISSUE THREAD

**Issue by MMeent** [kubernetes/dashboard#5451] opened 2020-08-20 19:16 UTC
##### Environment

```
Installation method: manual
Kubernetes version: 1.17.8
Dashboard version: 2.0.3
Operating system: Debian
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
1. Create a StatefulSet with `.spec.volumeClaimTemplates` configured.
2. Go to one of the pods in the UI, then click "delete pod".

##### Observed result
3. Observe that the PersistentVolumeClaim & PersistentVolume are deleted. The StatefulSet is now in a permanently broken state.

##### Expected result
3. Observe that the PersistentVolumeClaim & PersistentVolume are NOT deleted. The StatefulSet re-creates the now missing pod, and all is right with the world.

##### Comments
This dashboard-only behaviour is different from both the kubectl tool, and what I'd expect. StatefulSet-generated persistentVolumeClaims are annotated with `Reclaim Policy:  Retain`, so I really have no clue why you would delete them with the pod. Please fix.

**Comment by floreks** [comment] 2020-09-08 20:15
Since we are not doing anything explicitly, I am closing this as this is not a bug on our side. We'll think about changing the deletion policy in the new API.

/close

**Closed** 2020-09-08 20:15 UTC
Labels: kind/bug
