### ISSUE TITLE
Internal error [object Object]

### ISSUE THREAD

**Issue by hm400** [kubernetes/dashboard#4142] opened 2019-07-30 08:37 UTC
After deleting pod(s) dashboard throws 404 object Object internal error. Pod deletion is successful and it just throws error after 'clicking delete resource button.  
exec into pod from dashboard show cursor without prompt. Attached screenshots.
![dashboard-error](https://user-images.githubusercontent.com/47049792/62113966-a3330300-b283-11e9-9ba7-f4672ff71c14.png)
![dashboard-exec](https://user-images.githubusercontent.com/47049792/62113986-ac23d480-b283-11e9-87d7-6c6d8b52486f.png)

**Comment by floreks** [comment] 2019-07-30 08:39
Already fixed on master: https://github.com/kubernetes/dashboard/pull/4124

/close

**Closed by floreks** 2019-07-30 08:39 UTC

**Comment by hm400** [comment] 2019-07-30 09:19
Still receiving same error after updating dashboard to 2.0.0vbeta, k8 version 1.15.1
Should i try latest stable on 1.15?

**Comment by floreks** [comment] 2019-07-30 09:44
It's on the master, not yet released.

**Comment by middlestone** [comment] 2019-10-21 07:36
@floreks hi floreks, today I try the dashboard of 2.0.0beta5, which includes your fix. exec is normal now, but I still get the error of " internal server error" when delete pod.

**Comment by floreks** [comment] 2019-10-21 10:56
Not enough information.

**Comment by middlestone** [comment] 2019-10-21 11:38
hi floreks, please check the information below, thanks.

![image](https://user-images.githubusercontent.com/8234516/67201846-d1b31b00-f439-11e9-9ec3-937b68544982.png)

# kubectl get pods kubernetes-dashboard-54547d9cb8-8vlf2 -o yaml -n kubernetes-dashboard
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 192.168.250.240/32
  creationTimestamp: "2019-10-21T11:30:09Z"
  generateName: kubernetes-dashboard-54547d9cb8-
  labels:
    k8s-app: kubernetes-dashboard
    pod-template-hash: 54547d9cb8
  name: kubernetes-dashboard-54547d9cb8-8vlf2
  namespace: kubernetes-dashboard
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kubernetes-dashboard-54547d9cb8
    uid: 94ebe4bf-4bfe-4111-8d4a-4e1a219b60fa
  resourceVersion: "131084"
  selfLink: /api/v1/namespaces/kubernetes-dashboard/pods/kubernetes-dashboard-54547d9cb8-8vlf2
  uid: 248732c8-6e5e-4de4-9aae-2953e1024b62
spec:
  containers:
  - args:
    - --auto-generate-certificates
    - --namespace=kubernetes-dashboard
    image: kubernetesui/dashboard-arm64:v2.0.0-beta5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 30
    name: kubernetes-dashboard
    ports:
    - containerPort: 8443
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 2001
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /certs
      name: kubernetes-dashboard-certs
    - mountPath: /tmp
      name: tmp-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kubernetes-dashboard-token-kldh6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kylin
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: kubernetes-dashboard
  serviceAccountName: kubernetes-dashboard
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kubernetes-dashboard-certs
    secret:
      defaultMode: 420
      secretName: kubernetes-dashboard-certs
  - emptyDir: {}
    name: tmp-volume
  - name: kubernetes-dashboard-token-kldh6
    secret:
      defaultMode: 420
      secretName: kubernetes-dashboard-token-kldh6
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-10-21T11:30:09Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-10-21T11:30:11Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-10-21T11:30:11Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-10-21T11:30:09Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e9efca3cb55bd30c785e39f228123fce872458f36056342bbf3dfe78ec68d4e6
    image: dockerhub.azk8s.cn/kubernetesui/dashboard-arm64:v2.0.0-beta5
    imageID: docker.io/kubernetesui/dashboard-arm64@sha256:255e17ed6d43b54a6f712fb80d3b7fb18042e119748b9bd03a536399895ae31c
    lastState: {}
    name: kubernetes-dashboard
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-10-21T11:30:11Z"
  hostIP: 10.4.5.117
  phase: Running
  podIP: 192.168.250.240
  qosClass: BestEffort
  startTime: "2019-10-21T11:30:09Z"

**Comment by floreks** [comment] 2019-10-21 12:23
K8S version?

**Comment by middlestone** [comment] 2019-10-21 13:27
thanks floreks for your quick reply, it is 1.15.3 created by kubedm. btw, the pod is deleted successful, but dashboard still shows internal server error

**Comment by floreks** [comment] 2019-10-21 13:30
Try `v2.0.0-beta4`. `beta5` might not work as there were some breaking changes in `client-go` support for `v1.16`.

**Comment by middlestone** [comment] 2019-10-22 00:47
hi floreks, v2.0.0-beta4 fails too,  I have tried all versions of v2.0.0 from beta1 to beta5, no one works, :(

**Comment by floreks** [comment] 2019-10-22 08:19
Show console log.

**Comment by middlestone** [comment] 2019-10-22 08:58
hi floreks,  kubernetes-dashboard has tons of log, I only pick the piece shows that DELELTE operation is successful, if you need more, please tell me.

# kubectl logs kubernetes-dashboard-8fb689dff-6m2qf -n kubernetes-dashboard
.......
2019/10/22 08:46:47 Getting list of secrets in &{[default]} namespace
2019/10/22 08:46:47 [2019-10-22T08:46:47Z] Outcoming response to 10.4.5.117:4486 with 200 status code
2019/10/22 08:46:48 [2019-10-22T08:46:48Z] Incoming HTTP/2.0 DELETE /api/v1/_raw/pod/namespace/default/name/nginx-untrusted2 request from 10.4.5.117:4486:
2019/10/22 08:46:48 [2019-10-22T08:46:48Z] Outcoming response to 10.4.5.117:4486 with 200 status code
2019/10/22 08:46:52 [2019-10-22T08:46:52Z] Incoming HTTP/2.0 GET /api/v1/namespace request from 10.4.5.117:4486:
2019/10/22 08:46:52 Getting list of namespaces
2019/10/22 08:46:52 [2019-10-22T08:46:52Z] Outcoming response to 10.4.5.117:4486 with 200 status code

**Comment by floreks** [comment] 2019-10-22 09:33
I said console log, from the browser. Not the dashboard logs.

**Comment by middlestone** [comment] 2019-10-22 09:45
I am sorry for the mistake, do you mean the console log of the pod I used to reproduce this error？ if yes, please check the picture below.
![image](https://user-images.githubusercontent.com/8234516/67274492-21095200-f4f3-11e9-8e1a-6f6c07f59b87.png)

**Comment by floreks** [comment] 2019-10-22 14:30
![Zrzut ekranu z 2019-10-22 16-30-21](https://user-images.githubusercontent.com/2285385/67296802-44c79a80-f4e9-11e9-83b0-22f5b016ebbe.png)

**Comment by middlestone** [comment] 2019-10-24 01:15
hi floreks, I am sorry to reply late, and really appericate for your help. I have stopped to use 2.0.0-betaX, because there are so many small problems, such as the new one showed below.

![image](https://user-images.githubusercontent.com/8234516/67445206-a0f00300-f63e-11e9-9bb5-3191bf3c87af.png)

**Comment by FrVaBe** [comment] 2019-12-13 10:53
I have the same problem.
Dashboard Version: Dashboard v2.0.0-beta8+0.g4275399
Kubernetes Version: v1.13.1
Browser: Mizilla Firefox: 71.0 (64.Bit)

There is nothing logged to the console.
![grafik](https://user-images.githubusercontent.com/1521569/70794774-be1f9300-1d9e-11ea-9a70-cd52765faff8.png)

**Comment by djeeg** [comment] 2020-01-06 14:31
Getting the same on v2.0.0-beta8+0.g4275399 when doing trigger/delete actions
eg PUT https://site.domain.com/api/v1/cronjob/my-namespace/my-cronjob/trigger
The action does work okay.

Looking at the browser network trace, i see response type is x-gzip (whereas most other responses are json)
Response data in network trace is H4sIAAAAAAAE/........., is that gzipped base64?

Suggests a possible mismatch on the response content type for message display? 
(either the server sending or the client parsing)
