### ISSUE TITLE
Getting "400 Bad Request The plain HTTP request was sent to HTTPS port" when trying to access dashboard UI in browser

### ISSUE THREAD

**Issue by maisam94** [kubernetes/dashboard#9237] opened 2024-07-14 06:54 UTC
### What happened?

I upgraded to the 7.5.0 release of the helm chart for the k8s-dashboard. I am getting "400 Bad Request
The plain HTTP request was sent to HTTPS port" when loading the webpage for the UI in my browser.
I expected to see a login page where I can supply a token.

I did clean installation for the new helm chart with ingress enabled and a couple parameters defined such as annotations, ingress class name, host and lets-encrypt for ssl connection, but when trying to access the dashboard UI in my browser, I got "400 Bad Request ..."

These are the values that I am supplying to the helm chart:

app:
  ingress:
    useDefaultAnnotations: false
    enabled: true
    annotations:
      ingress.kubernetes.io/force-ssl-redirect:  'true'
      konghq.com/strip-path: 'true'
    ingressClassName: kong
    hosts:
      - k8s-new.app.xxx.com
    secretName: kubernetes-dashboard-tls
    issuer:
      name: letsencrypt-prod
    host: k8s-new.app.xxx.com

kong:
  enabled: true
  ingressController:
    enabled: true
  proxy:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
I would like to be able to reach the dashboard UI from outside the cluster via Https protocol with custom host.
so what should be configured or how would I point to kong proxy when using the ingress provided in the helm chart?

If there is any other information I can provide, please let me know. Thank you for your help!

### What did you expect to happen?

Access dashboard by HTTPS connection on web browser 

### How can we reproduce it (as minimally and precisely as possible)?

Enabling ingress with https connection and try to access the dashboard by web browser 

### Anything else we need to know?

Connecting  the dashboard by HTTP has success but when adding ingress and HTTPS Getting "400 Bad Request The plain HTTP request was sent to HTTPS port"

### Kubernetes Dashboard version

7.5.0

### Kubernetes version

1.28

**Comment by tbernacchi** [comment] 2024-07-16 16:25
You have to set [--insecure-port](https://github.com/kubernetes/dashboard/blob/master/docs/common/arguments.md#:~:text=Description-,insecure%2Dport,-8000) on your deployment `k edit deploy/kubernetes-dashboard-web -n kubernetes-dashboard` and then you have to deploy a certificate on your ingress. In this way as the error says "HTTP request was sent to HTTPS port" it's correct because the final destination it's 443. In this way I've suggested the certificate (https) will be in the first layer of your request. Ingress (https) -> svc -> pod (--insecure-port). Hope that helps you

**Comment by alessandroperetti** [comment] 2024-07-17 12:54
I solved upgrading  kong configuration through helm.
In particular you have to enable `kong.proxy.http.enabled`:

`helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard --set kong.proxy.http.enabled=true`

**Comment by floreks** [comment] 2024-07-18 07:52
This is a configuration issue, not a bug. If you need support, you can open i.e. a [discussion](https://github.com/kubernetes/dashboard/discussions). We do not provide support via issues.

/close

**Closed by floreks** 2024-07-18 07:52 UTC
Labels: kind/support
