### ISSUE TITLE
dashboard crash issue

### ISSUE THREAD

**Issue by grubin1989** [kubernetes/dashboard#2500] opened 2017-10-19 10:36 UTC
##### Environment

```
Dashboard version: 1.7.1
Kubernetes version: 1.7.8
Operating system: Ubuntu 16.04
Node.js version:
Go version: 1.8.3
```
status:
select a container and click the 'run command' in the right top corner then keep the page is opened.
using "kubectl apply -f" to update a pod , then dashboard will crash.

hope to resolve the problem,thanks.

**Comment by floreks** [comment] 2017-10-19 10:43
Not enough details about how to reproduce it. We need minimal step by step scenario that causes crashes. I have tested it with busybox and there are no problems. Dashboard is not crashing, only console connection is terminated.

**Comment by grubin1989** [comment] 2017-10-20 02:56
Sorry, that I will describe the problem more clearly makes you can  reappear the problem.
1. select a pod and click the "run command" link then it will jump to run command page with shell prompt which waits for you to input some commands, keep this page open.
2. change some parameters in  the deployment which creates the pod.
3. use "kubectl apply -f xxxx.yaml" to update the pod, then back to dashboard , the dashboad has no response.  it crashed.
in the third step, you can also modify the pod's deployment parameters  from dashboard ui, this has the same effect.

**Comment by floreks** [comment] 2017-11-10 06:47
I have checked this scenario using busybox image and can not reproduce.

**Comment by floreks** [comment] 2017-11-13 07:43
@maciaszczykm could you check above steps and see if you can reproduce this behavior? If not I'd close this issue unless some steps that can reproduce this behavior will be provided here.

**Comment by maciaszczykm** [comment] 2017-11-20 09:58
Cannot reproduce.

**Closed by maciaszczykm** 2017-11-20 09:58 UTC
