### ISSUE TITLE
"Sign in" in dashboard v2.0.0-beta6 not possible on new system - new attempt

### ISSUE THREAD

**Issue by kranzfr3d** [kubernetes/dashboard#4635] opened 2019-12-04 18:39 UTC
- got alternative.yaml:
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta6/aio/deploy/alternative.yaml
- edited dashboard-service with "type: NodePort":
kubectl -n kubernetes-dashboard edit service kubernetes-dashboard
- got port with: kubectl -n kubernetes-dashboard get service kubernetes-dashboard
- got brwoser with port
- sign in with correct token not possible

---------------

Installation method: kubernetes
Kubernetes version: GitVersion: v1.16.3
Dashboard version: v2.0.0-beta6
Operating system: Ubuntu 18.04.3 LTS
Node.js version ('node --version' output): v8.10.0
Go version ('go version' output): go version go1.10.4 linux/amd64

##### Steps to reproduce
get alternative.yaml, apply and expose

##### Observed result
- went with firefox and edge brwoser to:
http://172.16.1.20:32114/#/login
- put radiobutton down to "Token"
- copied token into "Enter token *"-field
- hit "Sign in"
- nothing happens, waited 30 seconds and longer
- hit "Sign in" again
- nothing happens
- hit "Sign in" again
- nothing happens

![2019-12-04 19_38_48-Window](https://user-images.githubusercontent.com/58233997/70170812-be000300-16cd-11ea-8051-94cfeb00cddd.png)

##### Expected result
Dashboard should appear after hitting "Sign in" button

##### Comments
Please help me, cannot enter dashboard, tried 5 days getting that thing working :-(
Please don't delete, if informations are missing I'm providing them as fast as possible!
Googling around & try&error did not help me :-(

**Comment by floreks** [comment] 2019-12-04 22:55
As I have already said in #4633, check other issues. This is in example a duplicate of https://github.com/kubernetes/dashboard/issues/4537. It's stated clearly why it doesn't work.

/close

**Closed by floreks** 2019-12-04 22:55 UTC
Labels: kind/bug

**Comment by kranzfr3d** [comment] 2019-12-04 23:58
I'm sorry, but 
kubectl port-forward -n kubernetes-dashboard service/kubernetes-dashboard 10443:80 --address 0.0.0.0
is NOT fixing this thing :-(

It says "Handling connection for 10443" but nothing happs on "Sign in", too :-(

/reopen please

**Comment by floreks** [comment] 2019-12-05 08:46
No. Read and understand what is written down in other issues. This is not a bug. Works as designed.

**Comment by kranzfr3d** [comment] 2019-12-05 09:42
Hi,

I sincerely thank you for answering and taking care of that and starting from me.
I understand you - you are a developer. the answer to questions like this one you go to the nuts.
please understand me too.
i would like to deal with kubernetes and do that intensively for a week. since days I am almost only on googlen and read at the github and now have a stable cubernet installation on my ubuntu server. A week is really not much, I am aware of that!
Everywhere I read that the dashboard is quite simple or starts without big problems. just log in and nice ... but yesterday you showed me the other post.
At some point I went through and wrote here because I really thought that the beta6 has a problem. but apparently it does not, as you have told me on several occasions.
I'd also like to access the dashboard, but I have a ubuntu server and can not access it from 127.0.0.1. Assuming that this works in the fewest cases, there must be another possibility.
From your point of view as a developer, the matter is quite simple. unfortunately not for me! I am really at the end.
can you please condescend and send me the command or command-lines that allows me to get the alternative dashboard to open from another system?
please do not answer with "works as designed", because I do not understand.

if sentences sound strange - i used the google translator to write these lines to me from the soul - because i really have a big problem with the dysfunctioning dashboard.
I have also failed to call the api https, because I get the following back, but that does not belong here, but is only for understanding why I try the alternative.yaml:
SSL_ERROR_RX_RECORD_TOO_LONG

I would like to thank you for your generosity, especially as it is already approaching Christmas with big steps.

Yours sincerely

**Comment by floreks** [comment] 2019-12-05 09:55
1. `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta6/aio/deploy/recommended.yaml`
2. `kubectl proxy` <--- do not change this line
3. Open http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
4. Log in with token.
5. Done.

**Comment by kranzfr3d** [comment] 2019-12-05 14:16
hi again,

ok, I installed mate-desktop onto my kubernetes master and firefox.
now I am able to access the dashboard.
Why you did not tell me, that the access isn't possible from any other machine directly, isn't it?

Yours sincerely

**Comment by floreks** [comment] 2019-12-05 15:39
> Why you did not tell me, that the access isn't possible from any other machine directly, isn't it?

It is possible... Only accessing Dashboard remotely when it's exposed over HTTP is blocked. You still haven't checked documentation and other issues.

**Comment by kranzfr3d** [comment] 2019-12-05 15:56
hi again,

got it to myself:
**https://stackoverflow.com/questions/39864385/how-to-access-expose-kubernetes-dashboard-service-outside-of-a-cluster**
with
kubectl -n kubernetes-dashboard edit service kubernetes-dashboard
and
kubectl describe services kubernetes-dashboard --namespace=kubernetes-dashboard

the port is saved on reboot.

**Comment by kranzfr3d** [comment] 2019-12-05 16:10
> It is possible... Only accessing Dashboard remotely when it's exposed over HTTP is blocked. You still haven't checked documentation and other issues.

hi,

ok, thats right, i'm not at the https/certificate part right now - i'm trying an other direction with docker first

**Comment by geckhan** [comment] 2019-12-25 09:59
I also encountered the same problem. I followed the master branch. The following is the return of http. Please tell me where the problem lies and how to solve it.

sign in (http://myip:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/api/v1/login) response is 
{
 "jweToken": "{\"protected\":\"eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0\",\"aad\":\"eyJleHAiOiIyMDE5LTEyLTI1VDEwOjAzOjI0WiIsImlhdCI6IjIwMTktMTItMjVUMDk6NDg6MjRaIn0\",\"encrypted_key\":\"Jm1Z3rm79SzlgWtMYqs3e2tNONHO2U7iIGRTk31gWvWJowSHKHk1FOBY639keddkrVIHT-P4wKfP5gCxlYty6y_Xab3ee5SqWKzu28hk-_4HchRxILuB8OfVL6nYE3KMLEx6rzIIgNWiSLB6IuOhCE8f3ZYByZqMjStyiPRXWhSFOBcYBlheJjJBa0SHLpEQuFKZqv2ywmqgRJjj_oPjNMvizEzc5IygVbCM9a-JBWpgQTaYwczqrVShxezVVFIXYB8f6i52CilnFDrZfgWDvjvnMjuH-49ZDC5QCh_pMKSlDNBBUpOsU-XL9gec7X7X3HqGJQ4IAiHsyBXMbDOwkg\",\"iv\":\"CH_yur635xq5Qvbe\",\"ciphertext\":\"Q6izqten9JsW8sx805uP0oEbKQg1Rm4imF8tzYQtd8o49pi5OLQBIpg4WJOsX0nzUUBMMqOtmI2rlYNEhcCynunFErekCJLkDMrv6as7u_WK7Tfo25LyqWDs8vgmhwOgbpmDwHVyjP0QWjqxUfJxS3NitQrvWs22TDhJ_ec_VqgohZK2K94TksHiwJ5SMwoDZG3n30TEfOG9UcGAlJCIgvixKD4mUYx8Fk9yKAXQWV5z9PE1_O94xCDpQS-dfdPyyTog62UUqlxOTg8dN-_bQX_wdLgDYWd3uJwCogkRY_eFOeaesLVz2Qasbrr0pstonlMafhRu7-tpSn2iaJyQOpoLuwssezhDvwpy9iwuxU1WmZm6mu4qOSddkp3l-yB75Zk157X1o-AIuM8RM0-kWGAtR_Xmmbe_XUt_lEmP2w2PL_-tYUphytTkMH3ZGzcc-a28qlooHya7w-fcwEkixCaH-yFeOiQKBaTqjzSPEYlaiDevVmL6ef1__gOgUm_c74QwFnVLz8wvW-ngHgSGroHi9xoHYUAVpbRzFt6So4eJGkbW7kgZjK2341TINiuLEKkbEDBx_C9vsnJDUARkJ8mpG4pz42uSJu9xWmk5gAsJId7t7HImxIhAiPRUzoX9GKxxvErPdssKnAmGg_CqfFebU7Tipf30n-a35U86SSrVS4iZz-eUj2cQTwFmmAMcWMY85Z2AdmANEaOM1M_0fYOV4gCsHhQk7NwHCivvRK1MJ5Khv15xbJsDtmvcmIj3bFQEwaVHoa5HBiL2V5f34pjKbj3GNTlp7MAVlKcDXf3MfKklMuxFlAiOE0RMICneuS_s9PQ9WSuZa_qZPSgAnZTklRwi8e1qloOkmpGCknZbjnrA7zx-mZdv_MGKyaMBaVJ29bMR3e5MD6a6tkVb2Gq33XKEf2zUdTLlTYPTmxOjlt9ucj9u_DKIuhfLxAb5FhioPcwfspe0HInL9Qt41hHmktzzCDGEPoxft8hC2WvNPDDqfD6gedKGY1jX9852OB1qwJk5sB02hQG_O4cyYmAQ9Xcvaa2bjSBo8a02NUdYYkUS4BQJae-5p55Q-rTXXfX-JbbwKzTFT4Z3MfnP4sL0tgTk0x2gYPr6x6_CrTZaKKhWoXHgKJAnd3wdAechQzsWGmv1mFhvnFSajvO9tdn_QIgdLC7z4PdWaPB6JbkUkbXFCF3u0WQVmTZDCapZ7iY8ozFLdy4r5w\",\"tag\":\"TfXBtcB8JJ9S1UQQY6HwDg\"}",
 "errors": []
}


and  config response http://myip:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/api/v1/plugin/config is  
{
 "status": 401,
 "plugins": [],
 "errors": [
  {
   "ErrStatus": {
    "metadata": {},
    "status": "Failure",
    "message": "MSG_LOGIN_UNAUTHORIZED_ERROR",
    "reason": "Unauthorized",
    "code": 401
   }
  }
 ]
}
