### ISSUE TITLE
Dashboard missing version and commit

### ISSUE THREAD

**Issue by OmgImAlexis** [kubernetes/dashboard#2030] opened 2017-06-16 08:20 UTC
##### Steps to reproduce

Goto about page. http://192.168.99.100:30000/#!/about?namespace=default

##### Environment
```
Installation method: Minikube on OSX
Kubernetes version:
Dashboard version: @@BUILD_DASHBOARD_VERSION
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result

![screen shot 2017-06-16 at 5 50 23 pm](https://user-images.githubusercontent.com/6525926/27218206-4f9b8a6a-52bc-11e7-9bf2-e00ad1e0d3c3.png)

**Comment by floreks** [comment] 2017-06-16 08:23
It's already fixed on master. Will be available in 1.6.2 release.

Duplicate of #2025.

**Closed** 2017-06-16 08:23 UTC
Labels: duplicate
