### ISSUE TITLE
Could not edit microservice deployment while uploading to kubernetes

### ISSUE THREAD

**Issue by liuben10** [kubernetes/dashboard#2441] opened 2017-10-04 17:55 UTC
##### Steps to reproduce
1. Delete old replica set for Authentication-service
2. Upload new replica set using kubectl create -f deploy.yml.
3. Click edit while connected to the Kubernetes dashboard via the kubernetes proxy and try to see the uploaded deployment version and then encounter this issue.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Not Found (404):
```
replicasets.extensions "authentication-service-2704063128" not found
```

**Comment by liuben10** [comment] 2017-10-04 18:31
Note this isn't a blocker. When I tried it again, it went through. I was just following the Error Notification prompt. I'm guessing that it was just because it was in the process of deleting the old replica set.

**Comment by floreks** [comment] 2017-10-05 08:11
Based on your description it is not a bug. 

1. You are on detail page of RS-A
2. You delete RS-A
3. You create RS-B
4. You are trying to do edit/reload or do something that requires RS-A.
5. Error not found is displayed.

```
replicasets.extensions "authentication-service-2704063128" not found
```

This error basically says that resource you were trying to access no longer exists and that is true since you have deleted it. New Replica Set was generated with same base name but different suffix. This is correct behavior and could only be partially avoided by implementing real time refresh in Dashboard. We already do have issue for that feature so I'm closing this.

PS. You might want to update dashboard to latest version. `v1.6.0` is quite old.

**Closed by floreks** 2017-10-05 08:11 UTC
