### ISSUE TITLE
Sort and pagination

### ISSUE THREAD

**Issue by Nox-404** [kubernetes/dashboard#3688] opened 2019-03-24 17:38 UTC
##### Environment

```
Installation method: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml`
Kubernetes version: `v1.13.4`
Dashboard version:` v1.10.1`
```

##### Steps to reproduce

* Start 15 pods
* Go to Settings and set the items per page to 50
* List pods
* Sort pods by names

##### Observed result

Upon listing you'll see all your pods, but as soon as you sort, you'll only see 10 pods instead of 50 and no controls to paginate

##### Expected result

See the full list filtered and maybe have the controls anyway

##### Comments

I've seen this behavior in pods, cm, secrets... But it seems ok in replication controller

**Comment by floreks** [comment] 2019-03-24 21:51
Duplicate of #3497 

/close

**Closed by floreks** 2019-03-24 21:51 UTC
Labels: kind/bug, triage/duplicate
