### ISSUE TITLE
Basic Authentication from Kubernete dashboard 

### ISSUE THREAD

**Issue by nagarjunra22** [kubernetes/dashboard#4952] opened 2020-02-26 18:52 UTC
Hi Team,

I like to sign in kubernetes dashboard with username and password instead of below token method.

Is this possible ? If yes,please advise with the steps

Regards

**Comment by floreks** [comment] 2020-02-26 21:00
Duplicate of #4951 

I'll answer there.

/close

**Closed by floreks** 2020-02-26 21:00 UTC
