### ISSUE TITLE
Default page size

### ISSUE THREAD

**Issue by c-knowles** [kubernetes/dashboard#1974] opened 2017-05-19 03:44 UTC
##### Environment
```
Dashboard version: 1.6.1
Kubernetes version: 1.6.2
```

##### Steps to reproduce
Browse any page of the dashboard on a larger screen size or screen in portrait mode.

##### Observed result
Quite a lot of wasted space in some cases, especially a portrait mode screen. In my case, around half the screen space in unused yet the default page size is quite small. The new search does help with this to filter.

##### Expected result
Allow a user to change the default page size from 10 items or maybe better would be to dynamically set the default page size based on the window size.

##### Comments
Maybe there are some other ways to increase screen usage?

**Comment by floreks** [comment] 2017-05-19 07:25
Duplicate of #1703. As I've mentioned in related issue this is on our roadmap and we will be working on introducing such a feature.

**Closed by floreks** 2017-05-19 07:25 UTC
Labels: duplicate

**Comment by c-knowles** [comment] 2017-05-19 09:49
@floreks thanks! Hadn't found that issue in my searches.
