### ISSUE TITLE
nginx-ingress requirement

### ISSUE THREAD

**Issue by jouve** [kubernetes/dashboard#8043] opened 2023-07-12 11:20 UTC
### What happened?

from v3 release note :
 > Kubernetes Dashboard now requires [cert-manager](https://cert-manager.io/docs/installation/) and [nginx-ingress-controller](https://docs.nginx.com/nginx-ingress-controller/installation/) to work properly.

but as far as I can [see](https://github.com/kubernetes/dashboard/blob/v3.0.0-alpha0/charts/helm-chart/kubernetes-dashboard/templates/networking/ingress.yaml) , the Ingress generated by the chart does not use nginx-ingress specific features (optionnaly adds nginx.ingress.kubernetes.io/ssl-redirect is the ingressClassName is nginx, so it won't even work if the ingress class a backed by nginx-controller, but is named something else).

### What did you expect to happen?

Explain that it requires an ingress controller (with default config with nginx, so might require adaptation)

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/kubernetes/dashboard/releases/tag/v3.0.0-alpha0

### Anything else we need to know?

I also find this a bad pratice to couple your project to the ingress controller implementation, k8s provides the Ingress abstraction to give user freedom of choice for the controller, and as a flaship k8s project, kubernetes/dashboard should respect that.

### Kubernetes Dashboard version

v3.0.0-alpha0

### Kubernetes version

na

**Comment by thrashwerk** [comment] 2023-07-12 11:50
The whole Kubernetes architecture is based around plugins (CNI, CSI, ingress, etc) so tying this chart to a specific implementation doesn't make any sense.

Why does it need nginx-ingress-controller specifically when any other ingress controller can provide the simple routing that's been used for years?

Why does it need cert-manager when ingress controllers can perform TLS termination?

Why make this project more complicated than it has to be?

**Comment by floreks** [comment] 2023-07-12 12:18
You can disable the nginx controller and use any other controller that will work properly with the Ingress resource. Everything should be templated in a way to allow you to change this. This is not a hard requirement. We have only used it as our default to make sure it works OOTB. cert-manager on the other hand could be more complicated to replace. We require Dashboard to be exposed via HTTPS by default and the easiest way to handle that without manual cert handling is with the manager.

**Comment by floreks** [comment] 2023-07-12 12:20
You can disable the nginx controller and use any other controller that will work properly with the Ingress resource. Everything should be templated in a way to allow you to change this. This is not a hard requirement. We have only used it as our default to make sure it works OOTB. cert-manager on the other hand could be more complicated to replace. We require Dashboard to be exposed via HTTPS by default and the easiest way to handle that without manual cert handling is with the manager.

I will replace "requires" with "uses" in the docs so it won't be that confusing.

**Comment by floreks** [comment] 2023-07-12 13:12
Sure they can, but we are using cert-manager to generate certificate used for external access. Our pods/services are using HTTP only for in-cluster communication and Ingress is combining them to be available under a single domain. It basically acts as an API gateway. You are free to disable cert-manager and provide your own custom certificate via secret, but it takes a bit more work to configure everything.

**Comment by arthurgeek** [comment] 2023-07-12 15:51
> You are free to disable cert-manager and provide your own custom certificate via secret

but only if the existing certificate secret is in the same namespace. or you need some sort of secret syncing.

in my case, I already have an issued cert, which is marked as [default cert for my existing `ingress-nginx`](https://github.com/arthurgeek/homelab/blob/main/kubernetes/apps/networking/ingress-nginx/app/helmrelease.yaml#L63). the problem is: even if I [disable `cert-manager` and `nginx`](https://github.com/arthurgeek/homelab/blob/main/kubernetes/apps/monitoring/kubernetes-dashboard/app/helmrelease.yaml#L58-L61), a [cert is still issued](https://github.com/kubernetes/dashboard/blob/master/charts/helm-chart/kubernetes-dashboard/templates/networking/ingress.yaml#L27-L39), while I wanted it to not issue any new cert at all, and let the default cert be used. With the default issuer `name` and `scope`, I couldn't get it to issue a valid cert. If I change it to use my existing issuer, then it still issue a new cert (unnecessarily), but it works.

> Our pods/services are using HTTP only for in-cluster communication

If you don't really need HTTPS, perhaps we want a new helm config value so it doesn't  issue a cert at all? (Or maybe add a new config requiring the user to provide their own cert, without having the dashboard issue one itself.

**Comment by floreks** [comment] 2023-07-12 17:28
IIUC you would like to be able to completely disable `cert-manager` annotation and only change certificate name to provide a custom one? I can easily add such option.

> If you don't really need HTTPS, perhaps we want a new helm config value so it doesn't issue a cert at all? (Or maybe add a new config requiring the user to provide their own cert, without having the dashboard issue one itself.

We do need Dashboard to be exposed externally via HTTPS, so a certificate is required. We can only change the way this certificate can be provided.

**Comment by arthurgeek** [comment] 2023-07-12 17:40
> IIUC you would like to be able to completely disable cert-manager annotation and only change certificate name to provide a custom one? I can easily add such option.

Correct. I'd like to skip any cert-manager annotations, so no new certs are issued.

> We do need Dashboard to be exposed externally via HTTPS, so a certificate is required. We can only change the way this certificate can be provided.

Gotcha! Then, it would be up to the user to ensure a new cert is issued and assigned to the ingress.

**Comment by floreks** [comment] 2023-07-13 07:42
Closing in favor of https://github.com/kubernetes/dashboard/issues/8048

/close

**Closed** 2023-07-13 07:43 UTC
Labels: kind/bug
