### ISSUE TITLE
ClusterShell web-terminal on the dashboard

### ISSUE THREAD

**Issue by johnmarcou** [kubernetes/dashboard#3629] opened 2019-03-04 06:22 UTC
##### What would you like to be added
I would like to suggest to implement a CloudShell feature on the dashboard.

##### Why is this needed
Some users would find handy to jump in a ClusterShell directly from the Dashboard UI to fire some `kubectl` commands. This would provide something like Cloud Shell from Google Cloud.

**Comment by floreks** [comment] 2019-03-04 08:14
Duplicate of #3431

/close

**Closed by floreks** 2019-03-04 08:14 UTC
Labels: kind/feature
