### ISSUE TITLE
Cannot access dashboard with no error

### ISSUE THREAD

**Issue by jhcpokemon** [kubernetes/dashboard#2540] opened 2017-11-03 07:35 UTC
##### Environment

```
Dashboard version:1.7.1
Kubernetes version:1.8.1
Operating system:CentOS 7.4.1708
Node.js version:
Go version:
```

##### Steps to reproduce

1.use kubeadm,install k8s 1.8.1,all green
2.deploy influxdb,grafana,heapster and up
2. `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml` deply dashboard
3.goto `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`
4.type in token in kubernetes-dashboard-token-xxxxx secret

##### Observed result

The dashboard login page has no response,.and dashboard log show that 
`2017/11/03 07:29:41 [2017-11-03T07:29:41Z] Outcoming response to 10.244.0.1:47609 with 200 status code
2017/11/03 07:29:41 [2017-11-03T07:29:41Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 10.244.0.1:47609: {}
2017/11/03 07:29:41 [2017-11-03T07:29:41Z] Outcoming response to 10.244.0.1:47609 with 200 status code`
##### Expected result

I expected to entry dashboard.

**Comment by maciaszczykm** [comment] 2017-11-03 08:20
> 4.type in token in kubernetes-dashboard-token-xxxxx secret

What exactly have you done in this step? You should copy one of secrets' token.

**Comment by jhcpokemon** [comment] 2017-11-03 09:39
I typed in the token of kubernetes-dashboard-token-jn7tx
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZC10b2tlbi1qbjd0eCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQ4OTU2Zjg4LWMwNmQtMTFlNy1hMmYwLTAwMGMyOWNhM2Y5MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTprdWJlcm5ldGVzLWRhc2hib2FyZCJ9.Q2o2pjdi65hwcZGntEuvT5ivbPAFpzbzLxkxDdepkPUtJKEQRMGGJUeyVOXWTXk2FMo6ZotTwX8_Up8qgt_nVcXllOktbQ9-OnP2DOn4J-3-bPSRgCd7BB7WUcZu1qZVyRlANsYyyhLLEOcdupcJTBAcM1aBrtePRLDKVSGT66IruTwBOs6jyU87Y4Jhm122qKMdLmDCDrVs64zBo0gqXUq-MO8cSuppBzzejZUuwvf6SPJZy95MSp8c54M1Ars_ncS8d74CXbZKyX-dPtsmjbt_9nkzb_21FegUo5F35u3-qJY3eOmnEr25Z8G47KYmWXCGP1T3PuVcHINQdbTB4w

**Comment by jhcpokemon** [comment] 2017-11-03 09:42
I edit kubernetes-dashboard service,change the service type from ClusterIP to NodePort,and access dashboard with the ip and port,in this case,everything is ok.

**Comment by gabrielfsousa** [comment] 2017-11-07 01:48
he service type from ClusterIP to NodePort wont work for me :( i cant telnet to he port :(

**Comment by maciaszczykm** [comment] 2017-11-07 08:00
@jhcpokemon What happens after filling token and confirming it with `Sign In` button?

**Comment by jhcpokemon** [comment] 2017-11-09 01:45
> What happens after filling token and confirming it with Sign In button?
Nothing happend,and no error in the chrome console.

**Comment by floreks** [comment] 2017-11-09 07:08
> Nothing happend,and no error in the chrome console.

This can only happen if you are exposing Dashboard using `kubectl proxy` and trying to access it from other machine, not using `localhost` or `127.0.0.1` as domain.

**Comment by jhcpokemon** [comment] 2017-11-10 03:05
Yes,I run the kubernetes cluster in my centos 7 virtual machine,and access the dashboard with the vm's IP,like this `192.168.189.129:9090/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login`

**Comment by floreks** [comment] 2017-11-10 06:20
Then this is the real reason. Your initial description was misleading:

> 3.goto 
`http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`

Logging in is only available when accessing Dashboard over HTTPS or when domain is either `localhost` or `127.0.0.1`. It's done this way for security reasons. Closing as this works as intended.

**Closed by floreks** 2017-11-10 06:20 UTC

**Comment by andrewsav-datacom** [comment] 2018-08-30 02:57
>Nothing will happen after clicking Sign in button on login page.


@floreks, why does it makes sense to ignore user actions? Would it be possible to display a error if something goes wrong?

**Comment by prashantcfc** [comment] 2018-12-28 20:57
@floreks I exposed the dashboard publicly which is running on my CentOS VM and can't sign in as it is over HTTP. How do I expose the dashboard over HTTPS ?

**Comment by AndrewSav** [comment] 2018-12-28 21:11
@prashantcfc the usual way, exactly the same way that you use for all you other applications. It's hard to give more precise instructions as this can be different depending on your environment and/or requirements. One common scenario is that you terminate SSL on your load balancer that is used to make your application (dashboard in this case) available to the app consumers.
