### ISSUE TITLE
Helm chart Kong crashes in GKE

### ISSUE THREAD

**Issue by regnaio** [kubernetes/dashboard#9052] opened 2024-05-17 00:07 UTC
### What happened?

Using:
- Helm chart version: `7.4.0`
- Kubernetes Dashboard version: `v3.0.0-alpha0`

No modifications were made to the default Helm template

```shell
$ kubectl get po -Aw

# kong CrashLoopBackOff
kubernetes-dashboard   kubernetes-dashboard-api-868bb8cf9c-k9bjb                        1/1     Running            0               7m59s
kubernetes-dashboard   kubernetes-dashboard-auth-566d8665d-hwdfl                        1/1     Running            0               7m59s
kubernetes-dashboard   kubernetes-dashboard-kong-76dff7b666-dsw7r                       0/1     CrashLoopBackOff   6 (102s ago)    7m59s # <--- CrashLoopBackOff
kubernetes-dashboard   kubernetes-dashboard-metrics-scraper-7f6f977dc9-l9wbc            1/1     Running            0               7m59s
kubernetes-dashboard   kubernetes-dashboard-web-7cccf8c454-hx6wp             1/1     Running            0               7m59s
---

$ kubectl logs -n kubernetes-dashboard kubernetes-dashboard-kong-76dff7b666-dsw7r

Defaulted container "proxy" out of: proxy, clear-stale-pid (init)
Error: could not prepare Kong prefix at /kong_prefix: nginx configuration is invalid (exit code 1):
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /kong_prefix/nginx.conf:7
nginx: the configuration file /kong_prefix/nginx.conf syntax is ok
nginx: [emerg] bind() to [::1]:8444 failed (99: Cannot assign requested address)
nginx: configuration file /kong_prefix/nginx.conf test failed


  Run with --v (verbose) or --vv (debug) for more details
```

### Kubernetes Dashboard version

Helm chart version: `7.4.0`
Kubernetes Dashboard version: `v3.0.0-alpha0`

### Kubernetes version

```shell
$ kubectl version

Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7-gke.1026000
```

**Comment by floreks** [comment] 2024-05-17 06:55
Duplicate of #8930, #8765

/close

**Closed by floreks** 2024-05-17 06:55 UTC
Labels: kind/bug

**Comment by CharlieC3** [comment] 2024-07-01 19:56
> I can work around this by modifying the Helm chart's default KONG_ADMIN_LISTEN value:
> 
> Default: 127.0.0.1:8444 http2 ssl, [::1]:8444 http2 ssl
> Changed: 127.0.0.1:8444 http2 ssl
> I think there's still something wrong here. I didn't have to do this change for DigitalOcean DOKS, but have to in GCP GKE

I was able to get around this by configuring the chart's values.yaml for both the `KONG_ADMIN_LISTEN` and `KONG_PROXY_LISTEN` as such:

```
proxy:
  addresses:
    - "127.0.0.1"
admin:
  addresses:
    - "127.0.0.1"
```

**Comment by rsalmond** [comment] 2025-10-06 16:37
For the folks who arrive here from a search: this is not a duplicate of #8765

Specifically, the port is not being used by another process. Rather the default values in the Kong helm chart (a dep of this project) assume the cluster has ipv6 support and if it does not have ipv6 support it will fail in a way that looks very similar to having a port in use conflict.

https://github.com/Kong/charts/issues/1073
https://github.com/kubernetes/dashboard/issues/9420#issuecomment-2333260346
https://github.com/kubernetes/dashboard/issues/9397#issuecomment-2317547934

Until a specific helm value for enabling ipv4 only mode arrives, the following values should help:

`--set kong.env.dns_order="LAST\,A\,CNAME\,SRV" --set kong.env.ADMIN_LISTEN="0.0.0.0:8444 http2 ssl"`
