### ISSUE TITLE
Dashboard fails to open after switching context

### ISSUE THREAD

**Issue by jacobcabantomski-ct** [kubernetes/dashboard#2847] opened 2018-02-21 02:44 UTC
##### Steps to reproduce

1. Switch k8s context.
2. Start dashboard proxy.
3. Go to `localhost:8001/ui`.
4. Do Stuff.
5. Kill dashboard proxy.
6. Switch k8s context again.
7. Start dashboard proxy.
8. Go to `localhost:8001/ui`.

##### Environment
```
Installation method: 
Kubernetes version: v1.9.2.gke-1
Dashboard version: v1.8.0
Commit: 054916b8fbadebd32dc16d32108fdd3c9ccbf400
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by maciaszczykm** [comment] 2018-02-21 08:00
Can you check it with v1.8.3 and `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy`/? `localhost:8001/ui` is deprecated.

**Comment by floreks** [comment] 2018-02-21 08:24
@jacobcabantomski-ct I think there were more steps. You have logged in using the first context, then switched to another context and it tried to decrypt JWE cookie with the invalid encryption key. We can wrap this error and show a different message.

**Comment by floreks** [comment] 2018-02-22 07:25
`/ui` endpoint was deprecated and will be removed in k8s 1.10. You should use full path to access the application through service. The reason was that API server should only serve as an API provider and not have any direct dependencies to applications that might not be deployed in the cluster thus making such aliases invalid.

**Comment by cgdobre** [comment] 2018-05-03 14:51
I can't get around this issue. Do you have a clear reproducible set of steps to solve the issue when it occurs ?

**Comment by jacobcabantomski-ct** [comment] 2018-05-03 19:42
@cgdobre I ended up skipping the auth (token/kubeconfig) process and using the default (default service account)

![image](https://user-images.githubusercontent.com/21041380/39599073-d2e00410-4ed7-11e8-802b-b266509c022b.png)

![image](https://user-images.githubusercontent.com/21041380/39598976-8bd8dcc2-4ed7-11e8-9d20-66dbb4bef668.png)

![image](https://user-images.githubusercontent.com/21041380/39599014-a5af994c-4ed7-11e8-8522-449f59e12c90.png)

This has been working for me thus far, but I believe is only working as we haven't fully hardened/secured our k8s instance via recommendations in https://cloudplatform.googleblog.com/2017/11/precious-cargo-securing-containers-with-Kubernetes-Engine-18.html

**Comment by floreks** [comment] 2018-12-13 13:58
Closing in favor of #3417

**Closed by floreks** 2018-12-13 13:58 UTC
Labels: kind/bug, lifecycle/frozen
