### ISSUE TITLE
Dashboard does not work with kubectl proxy --api-prefix

### ISSUE THREAD

**Issue by ashafer01** [kubernetes/dashboard#5026] opened 2020-03-23 23:25 UTC
##### Environment

```
Installation method: recommended.yaml
Kubernetes version: 1.15 / EKS
Dashboard version: 2.0.0rc6
```

##### Steps to reproduce

1. Install dashboard following 2.0.0-rc6 Getting Started instructions in README
2. Pass an API prefix to proxy command, e.g. `--api-prefix /foo`
3. Access the localhost address given in README except with the path prefixed with `/foo`

##### Observed result

The browser viewport appears blank white. The JS console shows several errors and script load failures. The resource URLs in the error messages do not include the API prefix.

##### Expected result

`--api-prefix` should work transparently as in v1 dashboard.

##### Comments

We use the api prefix to manage connecting to dashboards on multiple clusters. This is essential to our workflow.

**Comment by floreks** [comment] 2020-03-24 10:40
Duplicate of #5017 
Fixed already by #5022 

/close

**Closed** 2020-03-24 10:40 UTC
Labels: kind/bug
