### ISSUE TITLE
Dashboard reported Forbidden Error - New Installation using kubeadm 1.6.1 on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by BCoskun** [kubernetes/dashboard#1815] opened 2017-04-04 16:36 UTC
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list jobs.batch in the namespace "default". (get jobs.batch)
```

**Comment by BCoskun** [comment] 2017-04-04 16:37
I noticed this is duplicate #1810

**Comment by BCoskun** [comment] 2017-04-04 16:46
Sorry, I thought this error and #1810 is similar but after I rechecked #1810 again, It seems error messages are different and may be be message on this error more helpful to developer so re-open it.

**Comment by floreks** [comment] 2017-04-04 17:11
It is a duplicate of #1800 and related to #1803.

**Closed by floreks** 2017-04-04 17:11 UTC
