### ISSUE TITLE
is it really noway for username and password login?

### ISSUE THREAD

**Issue by willzhang** [kubernetes/dashboard#6363] opened 2021-08-18 06:45 UTC
##### What would you like to be added
login with username or password

see below ,all basic auth is deprecated since Kubernetes v1.19
https://stackoverflow.com/questions/68634196/basic-auth-in-kubernetes-dashboard-helm-deployment

##### Why is this needed
Who uses token or kubeconfig every time they log in? No user name and password login dashboard is just a toy and has no practical use

it not like lens or kubectl command, lens or kubectl will Save kubeconfig at local, but dashboard can do nothing ,you must save token to somewhere and paste it everytime, It's too cumbersome for a web login

so why can not dashboard itself support username and password login, is it a really Difficult things?

**Comment by floreks** [comment] 2021-08-18 15:17
> is it a really Difficult things?
Yes, and it is also time-consuming to provide proper support for it later on. Especially, when you can already configure reverse OAuth proxy in front of Dashboard and use whatever you want to have username/password-based login. 

If you think however that it is not difficult, then you are always welcome to create a PR that will add support for this.

 > No user name and password login dashboard is just a toy and has no practical use
I think our usage statistics would beg to differ. 🤷   

There are dozens of ways to configure Dashboard and be able to use username/password login. There are also lots of already closed issues that talk about this topic.

As this issue is not really helpful and basically the feature request is a duplicate of what is already described in https://github.com/kubernetes/dashboard/issues/2353 I am closing this one.

/close

**Closed** 2021-08-18 15:17 UTC
Labels: kind/feature
