### ISSUE TITLE
Can't sign in into dashboard

### ISSUE THREAD

**Issue by TriggMineAdmin** [kubernetes/dashboard#2735] opened 2018-01-05 11:28 UTC
```
Dashboard version: 1.8.1
Kubernetes version:  1.9.0
Operating system: Ubuntu Ubuntu 16.04.3 LTS
```

##### Steps to reproduce
1. Clean installation of kubernetes cluster
2. ```kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml```
3. Take token by this manual https://github.com/kubernetes/dashboard/wiki/Access-control
```kubectl -n kube-system get secret```
```kubectl -n kube-system describe secret kubernetes-dashboard-token-lx6wf```
4. ```kubectl proxy --address='0.0.0.0' --port=8001 --accept-hosts='^*$'``` (only for test)
5. Open ```http://myip:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login```
6. Change radio to "Token" and paste token from step 3
##### Observed result
When i press "Sign in" nothing happens. 
Browser console:

![image](https://user-images.githubusercontent.com/13350250/34607417-2df95f7c-f21c-11e7-8d6b-ad8b7d2161ac.png)

**Comment by floreks** [comment] 2018-01-05 12:55
Duplicate of #2524 and possibly some others.

https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above

> NOTE: Dashboard should not be exposed publicly using kubectl proxy command as it only allows HTTP connection. For domains other than localhost and 127.0.0.1 it will not be possible to sign in. Nothing will happen after clicking Sign in button on login page.

**Closed by floreks** 2018-01-05 12:55 UTC

**Comment by idevz** [comment] 2018-01-16 15:13
cool,thanks :)

**Comment by ashish235** [comment] 2018-06-04 10:41
Cool. I 'm the same issue. So that being said, how do I access the dashboard if not by kubectl proxy? I 'm using AWS instances, so can't have a web interface on localhost. 

On the dashboard URL, returned from cluster-info, I 'm not getting any login page, just unauthorized in json.

**Comment by rpocklington** [comment] 2018-06-05 18:34
Seconding ashish235's comment.

**Comment by apoms** [comment] 2018-07-05 17:15
I had the same issue as @ashish235. How I solved it:

Run `kubectl proxy` as normal on your AWS instance. Now, on your local machine, port forward the proxy port (usually 8001) so that you can access it from localhost:

```
ssh -L 8001:localhost:8001 <user@server-ip>
```

You should now be able to access the dashboard using your browser at `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login`

**Comment by sunilram86** [comment] 2018-08-31 19:47
@apoms - the above solution works like a charm... I used the same approach for accessing the dashboard built for my EKS cluster... I had installed kubectl & config on a AWS server so that my team can ssh into it via jump box. After port forwarding it, can open it via local machine on a browser.

**Comment by ysjiang4869** [comment] 2018-09-05 03:10
Let me have a summary:
if you use [recommend](https://github.com/kubernetes/dashboard/blob/master/src/deploy/recommended/kubernetes-dashboard.yaml) yaml to deploy dashboard, you should only access your dashboard by https , and you should generete you certs, refer to [guide](https://github.com/kubernetes/dashboard/wiki/Installation)
then , you can run ```kubectl proxy --address='0.0.0.0' --accept-hosts='^*$'``` to visit dashboard on "http://localhost:8001/ui" . This page need to login use token, generete refer to [this page](https://github.com/kubernetes/dashboard/wiki/Creating-sample-user). Also you can add NodePort to you yaml and access to it use <nodeip>:<port>

if you deploy use [http alternative](https://github.com/kubernetes/dashboard/blob/master/src/deploy/alternative/kubernetes-dashboard.yaml) method, you can **only access your dashboard by \<nodeip\>\:\<port\>**, remeber to add it to yaml first!!
After deploy, you should also generate you token and **add header ```Authorization: Bearer <token>``` for every request**.

The offical wiki is a little bit confused so I reordered it here.

**Comment by YanB25** [comment] 2019-03-19 08:20
Thank you very much. They help. 
Also, I think it could be better if an error message show up when I click `sign up` and fail.

**Comment by floreks** [comment] 2019-03-19 09:01
> if you deploy use http alternative method, you can only access your dashboard by <nodeip>:<port>, remeber to add it to yaml first!!
After deploy, you should also generate you token and add header Authorization: Bearer <token> for every request.

That is not correct. Alternative method is there if user wants to use his own reverse proxy and external IdP to configure access to the cluster.

**Comment by balajipothula** [comment] 2019-06-22 14:54
Thank you so much apoms <Alex Poms>
I spend a lot of time. Love you buddy :)

**Comment by develar** [comment] 2019-06-22 17:32
So, it is not possible to use k8s dashboard and multipass without such hacks or extra configuration. So, [Kubernetic](https://kubernetic.com/) can be an alternative, you just need to configure local kubectl:

`multipass exec build-service -- /snap/bin/microk8s.config > ~/.kube/config
`

(to install kubectl on macOS: `brew install kubectl`).

**Comment by pingoleon108** [comment] 2020-06-26 22:34
You need just 2 commands:



$ kubectl port-forward svc/kubernetes-dashboard -n kube-system 6443:443




ssh -i EC2KeyPair.pem ec2-user@IP -L 6443:127.0.0.1:6443

**Comment by korncola** [comment] 2021-05-01 18:27
Sort your mess out and display something on the login page when a user tries to login via http from a remote host. Just let the sign in button do nothing is confusing and buggy.
**And make a documentation, that worthy to be called documentation.** The whole k8s doc is just a terse misleading wannabe documenation.
