### ISSUE TITLE
Error running a development Kubernetes cluster with gulp task

### ISSUE THREAD

**Issue by preillyme** [kubernetes/dashboard#549] opened 2016-03-18 18:12 UTC
#### Issue details

```
$ gulp local-up-cluster
[11:08:18] Requiring external module babel-register
[11:08:20] Using gulpfile ~/code/dashboard/gulpfile.babel.js
[11:08:20] Starting 'spawn-cluster'...
[11:08:20] Starting 'wait-for-cluster'...
[11:08:20] Starting 'wait-for-heapster'...
[11:08:21] Finished 'spawn-cluster' after 501 ms
[11:08:21] Waiting for a Kubernetes cluster at http://localhost:8080...
[11:08:21] Waiting for a Heapster ...
undefined:1
404: Page Not Found
   ^

SyntaxError: Unexpected token :
    at Object.parse (native)
    at cluster.js:73:27
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```
##### Environment

```
Dashboard version: commit 6937a5a5f3f810f862b41bba8edde3e0eade2200
Kubernetes version: 1.1.2
Operating system: Ubuntu 15.10
Node.js version: v5.9.0
Go version: go version go1.6 linux/amd64
```

**Comment by preillyme** [comment] 2016-03-18 19:42
I can confirm that `heapster:v0.20.0-alpha9` is running.

```
curl http://localhost:8082/api/v1/model/debug/allkeys
[
  "node:127.0.0.1/container:docker-daemon",
  "node:127.0.0.1/container:docker/f554eca21bfea905edb4ea221423921a9ff7943449bf127154afbc3fbef60160",
  "node:127.0.0.1/container:user.slice/user-1000.slice",
  "node:127.0.0.1/container:user.slice/user-1000.slice/session-8.scope",
  "node:127.0.0.1/container:user.slice/user-1000.slice/user@1000.service",
  "node:127.0.0.1/container:docker/f554eca21bfea905edb4ea221423921a9ff7943449bf127154afbc3fbef60160/kube-proxy",
  "node:127.0.0.1/container:docker/f16be901c68ba23f11154255a1e7a608ea5b31d7fbda0e34e159149ca938d86b",
  "node:127.0.0.1/container:docker/854011cdfbb24a70d8b8250b19b5676560fc3321dd86be3c65353e7ab9c1ed65",
  "node:127.0.0.1/container:user.slice",
  "node:127.0.0.1/container:docker/f7d97d4b8a701d4b23671c45cf85b12d231f8ae89f7c2f476e6147386900d205",
  "node:127.0.0.1/container:user.slice/user-1000.slice/session-5.scope",
  "node:127.0.0.1/container:user.slice/user-1000.slice/session-2.scope",
  "node:127.0.0.1/container:docker/5bf9679f6265a33c98b69af79a0bb220f635cef18eae3d0f3c56a24e10f61273",
  "node:127.0.0.1/container:docker/fbef807806da182add1aac060dfbf83de7d006025b97c15a340f6686a192ba5a",
  "node:127.0.0.1/container:docker/6b9c5873e922bf1d05b13dab1b7a4626d5c6655cae9a5b262661d60e87186156",
  "node:127.0.0.1/container:system.slice",
  "cluster",
  "node:127.0.0.1/container:docker",
  "node:127.0.0.1/container:docker/93aef6a2ebbb39662aeda2f70a4d8f49ce5a13315a14d33653a65366fc310d11",
  "node:127.0.0.1/container:user.slice/user-1000.slice/session-3.scope",
  "node:127.0.0.1",
  "node:127.0.0.1/container:kubelet"
```

**Comment by preillyme** [comment] 2016-03-18 20:02
I don't seem to find that endpoint in: https://github.com/kubernetes/heapster/blob/master/docs/storage-schema.md

**Comment by cheld** [comment] 2016-03-20 08:17
Hmm...I have an idea....are you running something on port 8080? Gulp is waiting for Kubernetes to respond on port 8080. BTW: you can run the containers directly with the script build/hypercube.sh - might simplify your debugging attempts.

**Comment by preillyme** [comment] 2016-03-20 15:13
@cheld nothing else is running on port 8080 and the services successfully start as expected. The issue is that the script is unable to parse the `404: Page Not Found` error that is encountered from `heapster:v0.20.0-alpha9` which is running on `http://localhost:8082` it appears that the script is attempting to access an endpoint that doesn't exist. Do you mind trying a fresh checkout at `commit 6937a5a5f3f810f862b41bba8edde3e0eade2200` and attempt to run `$ gulp local-up-cluster`.

**Comment by cheld** [comment] 2016-03-21 07:40
Ah ok, I see. But I cannot reproduce - kind of. The cluster starts without an error message. But a manual check of the health-check url fails...I will investigate...

**Comment by bryk** [comment] 2016-03-21 11:04
@cheld I'm assigning this to you. Please work with @preillyme, because we really want to have dev instructions that actually work :)

**Comment by cheld** [comment] 2016-03-21 15:18
I can reproduce now with the following steps:

gulp local-up-cluster
docker kill $(docker ps -q)
gulp local-up-cluster

**Comment by cheld** [comment] 2016-03-29 12:04
The problem was caused by:
1. Incorrect error handling
2. The health check URL was not updated after upgrading Heapster

Fixed

**Closed by cheld** 2016-03-29 12:04 UTC
Labels: area/dev, kind/bug, priority/P2
