### ISSUE TITLE
CPU Usage and Memory Usage graphs issue

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes/dashboard#5236] opened 2020-06-05 12:24 UTC
##### Environment
Dashboard: v2.0.1+0.g5b83803
Google Chrome: 83.0.4103.97 (Official Build) (64-bit)

##### Steps to reproduce
Open the Dashboard in Chrome, set the viewport to an horizontal size in this interval: 1711px to 1725px

##### Observed result
The CPU Usage and Memory Usage getting crazy.
Easy way to show it https://www.youtube.com/watch?v=7OhzK_w4u4Q

##### Expected result
Static graph

**Comment by floreks** [comment] 2020-06-05 12:31
Duplicate of #5118, #5102, #5050 

/close

**Closed** 2020-06-05 12:31 UTC
Labels: kind/bug

**Comment by pierluigilenoci** [comment] 2020-06-05 12:49
@floreks sorry for that... I tried to search for an open ticket on this issue but I was not able to find it. Now I understood why. They are all closed. 😅

**Comment by floreks** [comment] 2020-06-05 12:58
No worries, I remember most issues so I can quickly triage them :slightly_smiling_face:

**Comment by pierluigilenoci** [comment] 2020-06-05 12:58
Also duplicate of https://github.com/kubernetes/dashboard/issues/5101, https://github.com/kubernetes/dashboard/issues/5106

This seems like a fairly widespread problem. 😆 
I'm sorry I helped make noise.

**Comment by floreks** [comment] 2020-06-05 13:02
Unfortunately, yes. Maybe this will influence chart library maintainers to look at this problem sooner.

**Comment by pierluigilenoci** [comment] 2020-06-05 13:11
I checked on ngx-charts repo. They have a already couple of open issues (https://github.com/swimlane/ngx-charts/issues/349 and https://github.com/swimlane/ngx-charts/issues/971) for this, the older one since April 2017.

I see little hope in a short resolution. 😞 

Personal remark: considering that the project has the last commit of almost two months ago and bugs of this kind are ignored perhaps it is not the best framework for the needs of the Dashboard. Fortunately, the intervals in which the problem is generated are limited but... 😢

**Comment by floreks** [comment] 2020-06-05 13:16
We have already tried 3 different chart libraries before this one and it seems to be the easiest to use and most stable, despite this one issue.

**Comment by pierluigilenoci** [comment] 2020-06-05 13:23
Ok, I tried to ping those who seem to be the most involved contributors in the library, let's see what happens. 

Just for fun... sometimes this library creates some artifacts in the drawing, actually inventing time travel... 🤣 

![Screenshot 2019-07-29 at 12 07 34](https://user-images.githubusercontent.com/36044817/83881051-5f7d1580-a740-11ea-9898-55e471048ef3.png)
![Screenshot 2019-07-29 at 12 02 54](https://user-images.githubusercontent.com/36044817/83881063-64da6000-a740-11ea-8e6a-695121061fdc.png)

**Comment by floreks** [comment] 2020-06-05 14:16
Seems like you have tweaked metrics scraper to scrape metrics more frequently or metrics scraper failed to gather metrics for few minutes. The approximation function used by the ngx to draw the line is not prepared for that I guess.
