### ISSUE TITLE
Pod count should be trimmed

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#434] opened 2016-02-25 13:01 UTC
#### Issue details
leading or trailing spaces should be ignored. Similar behavior at Gmail

##### Steps to reproduce
1. Open deploy from settings
2. Enter "5 " as number of pods

##### Observed result
validation error

##### Expected result
ok

##### Comments
visually the input seems correct. So, the validation message is not understandable

**Comment by cheld** [comment] 2016-02-25 13:02
Same for many other fields

**Comment by bryk** [comment] 2016-03-01 08:25
I cannot reproduce on Chrome. What's your browser?

**Comment by cheld** [comment] 2016-03-04 09:16
Sorry. I could not reproduce on Chrome either. I tested with Firefox 44 on Ubuntu

**Comment by bryk** [comment] 2016-03-04 11:09
Closing.

**Comment by cheld** [comment] 2016-03-04 13:58
Sorry for confusion.

- The bug is not reproducible on Chrome
- The bug IS reproducible on Firefox.

Low prio, though

**Comment by maciaszczykm** [comment] 2016-03-10 08:59
I've done pretty much investigation in this matter and it won't be easy to fix. To be honest I think we shouldn't fix it at all, because it's Firefox bug, not ours.

Firefox doesn't fully implement `<input type="number">` behaviour. It performs number validation on input field, but it doesn't filter aplha and whitespace characters. Moreover, it seems to be not only one missing thing. 

I've tried to create new directive `kd-numbers-only` and use it everywhere to ensure, that fields will work in the same way on every browser:

``` javascript
export default function numbersOnlyDirective() {
  return {
    require: 'ngModel',
    link: function (scope, element, attr, ngModelCtrl) {
      function filterInputValue(inputValue) {
        if (inputValue) {
          var transformedValue = inputValue.replace(/[^0-9]/g, '');
          if (transformedValue !== inputValue) {
            ngModelCtrl.$setViewValue(transformedValue);
            ngModelCtrl.$render();
          }
          return transformedValue;
        }
        return undefined;
      }
      ngModelCtrl.$parsers.unshift(filterInputValue);
    }
  };
}
```

Unfortunately providing whitespaces don't execute it on Firefox, only alpha characters. Moreover to make it work there was a need to switch `<input type="number">` to `<input type="text">`.

There are too much issues with it on Firefox, that I believe we shouldn't create big workarounds just to make it work. I'd create a bug for it and perhaps change message to warn user about possible issues (there is even specific attribute for Firefox to display custom message only for it).

CC @floreks @bryk @cheld

**Comment by floreks** [comment] 2016-03-10 09:09
If this is an issue with firefox `type="number"` implementation then this should be reported in there as a bug. Forcing this workaround will make code less readable and soon we may end up with many workarounds for specific browsers that will complicate the code and lower its quality.

**Comment by maciaszczykm** [comment] 2016-03-10 09:56
Adding `<ng-messages>` would require disabling default HTML5 validation with `novalidate`, and disabling `OK` button if validation result is false.

Other possible solution is adding `x-moz-errormessage="Must be positive number"`. It would create custom message for Firefox browser.

Which one seems to be more suitable for you?

**Closed** 2016-03-11 08:34 UTC
Labels: area/validation, kind/enhancement, priority/P3
