### ISSUE TITLE
Selecting "All namespaces" on a large cluster causes OOMkill

### ISSUE THREAD

**Issue by davidtseng** [kubernetes/dashboard#5318] opened 2020-06-30 00:07 UTC
##### Environment

```
Installation method: Kubespray on self-hosted AWS
Kubernetes version: v1.17.7
Dashboard version: v2.0.3
Operating system: Flatcar Container Linux 2512.2.1
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

On our large development cluster (over 3000 deployments, 700 namespaces) selecting "All namespaces" in the namespaces dropdown menu for workloads

##### Observed result

Cronjobs (we have 3) returns quickly but the other resources spin with loading animation and eventually show "Internal error 500" and show OOMKilled in pod description. We tried raising the limit for kubernetes-dashboard to 12G but still get the error eventually.

##### Expected result

Details similar to a smaller cluster.

##### Comments

A developer on our end looked for a workaround and reported: I couldn't find workaround. I see that it tries to load resources/metrics for every workload in all namespaces when you select all-namespaces... Only way I saw to remove the option is to edit source and build/deploy.

An option to hide the "All namespaces" option in settings would be useful in the short term.

**Comment by davidtseng** [comment] 2020-06-30 00:18
Note: I am also seeing this on a smaller cluster (159 deployments, 184 namespaces) with 2G limit for dashboard.

**Comment by floreks** [comment] 2020-06-30 06:51
First disable resource autorefresh in settings. This should help.

**Comment by floreks** [comment] 2020-06-30 11:56
Duplicate of https://github.com/kubernetes/dashboard/issues/5197

/close

**Closed** 2020-06-30 11:56 UTC
Labels: kind/bug
