### ISSUE TITLE
No items displayed in tables if clusterName set

### ISSUE THREAD

**Issue by stephan2012** [kubernetes/dashboard#6637] opened 2021-11-25 15:49 UTC
##### Environment

```
Installation method: Helm chart
Kubernetes version: v1.19.16
Dashboard version (v1.x is not supported. Use v2.0 or later.): v2.4.0
Operating system: Ubuntu 18.04.6 LTS
Node.js version ('node --version' output): (official Docker image kubernetesui/dashboard:v2.4.0)
Go version ('go version' output): (official Docker image kubernetesui/dashboard:v2.4.0)
```

##### Steps to reproduce

When setting `.settings.clusterName` via Helm chart 5.0.4, the dashboard shows the number of elements, but no data in the tables (see attached screenshot).

![k8s_dashboard_empty](https://user-images.githubusercontent.com/3070471/143470535-e0f4e8de-b7c5-45e4-8ee8-e3752866b9ca.png)

The chart creates a configMap containing:

```yaml
data:
  _global: '{"clusterName":"k8s"}'
```

Removing the setting (i.e., setting `data` to `{}`) makes the dashboard work.

##### Observed result

Dashboard shows the number of items, but no actual items.

Quite interesting: When doing many reloads of the page in the web browser, the dashboard _sometimes_ shows data in the tables (every 6th to 10th attempt).

##### Expected result

Dashboard displays the cluster name _and_ shows data. ;-)

##### Comments

Confused. Is there any documentation for the settings?

**Comment by floreks** [comment] 2021-11-29 09:30
Duplicate of https://github.com/kubernetes/dashboard/issues/6282

/close

**Comment by floreks** [comment] 2021-11-29 09:34
Actually, my comment from https://github.com/kubernetes/dashboard/issues/6282#issuecomment-906689744 is not solved. I will reopen to keep track of it.

/reopen

**Comment by stephan2012** [comment] 2021-11-29 11:24
Well, after reading #6282 I’m really wondering why an externally provided config is not merged with the applications defaults. This is absolutely counterintuitive and I do not know any other recent application behaving this way. Instead, it is quite natural to only pass values that you want to override. This also improves forward compatibility when new settings are introduced for the dashboard. Just

> helm config to contain all settings and a comment no to remove any of them

is really an attempt to cover bad application design. :-(

**Closed** 2021-12-22 08:55 UTC
Labels: kind/bug
