### ISSUE TITLE
Unable to access to kubernetes dashboard 

### ISSUE THREAD

**Issue by thelastworm** [kubernetes/dashboard#1808] opened 2017-04-03 12:09 UTC
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list jobs.batch in the namespace "kube-system". (get jobs.batch)
```

**Comment by maciaszczykm** [comment] 2017-04-03 12:09
Duplicate of #1800.

**Closed by maciaszczykm** 2017-04-03 12:09 UTC

**Comment by maciaszczykm** [comment] 2017-04-03 12:10
Check also #1803.
