### ISSUE TITLE
Missing YAML file 

### ISSUE THREAD

**Issue by owainlewis** [kubernetes/dashboard#2386] opened 2017-09-20 07:46 UTC
The documentation in README.md mentioned using a no-rbac version of the dashboard. This used to work but appears to have been removed.

##### Steps to reproduce
kubectl create -f https://git.io/kube-dashboard-no-rbac

##### Observed result
YAML does not exist. 404

**Comment by floreks** [comment] 2017-09-20 07:50
Duplicate of #2370

**Closed by floreks** 2017-09-20 07:50 UTC
Labels: duplicate
