### ISSUE TITLE
Dashboard reported Forbidden (403)

### ISSUE THREAD

**Issue by jsl9208** [kubernetes/dashboard#1840] opened 2017-04-11 07:10 UTC
Hello, I'm getting 403 error on dashboard. It reported **User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)**. Does it relate to RBAC or flannel?

##### Steps to reproduce

1. Init the master `kubeadm init --pod-network-cidr 10.244.0.0/16`
2. Install flannel addon 
    ```
    kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml
    kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    ```
3. Install dashboard 
    ```
    kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
    ```
4. Run proxy command
    ```
    kubectl proxy
    ```
5. Open http://localhost:8001/ui in browser

##### Environment
```
Kubernetes version: v1.6.0
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)
```

**Comment by rootsongjc** [comment] 2017-04-12 06:32
+1 
**Kubernetes services**
```
kubectl cluster-info
Kubernetes master is running at https://172.20.0.113:6443
KubeDNS is running at https://172.20.0.113:6443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://172.20.0.113:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
```
**Details**
Open `https://172.20.0.113:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard` in brower.
```
User "system:anonymous" cannot proxy services in the namespace "kube-system".
```
**Environment**
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
Open 172.20.0.113:nodePort in browser.
**Observed result**
```
Forbidden (403)

User "system:serviceaccount:kube-system:default" cannot list jobs.batch in the namespace "default". (get jobs.batch)
```

**Comment by floreks** [comment] 2017-04-12 07:16
Duplicate of #1800. Related to #1803.

**Closed by floreks** 2017-04-12 07:16 UTC

**Comment by ramiz99** [comment] 2018-01-16 16:08
Just a note - this was one of the only issues i could find relating to something i was fighting. 

My issue was that i had the config on the wrong context- switched to the right one and it worked fine. Check your context

good luck
