### ISSUE TITLE
Select multiple objects and perform batch actions on it

### ISSUE THREAD

**Issue by hadim** [kubernetes/dashboard#5239] opened 2020-06-07 16:29 UTC
It would be nice to be able to select multiple objects at once and perform batch actions on it.

A typical use case is to select multiple pods and delete them or restart them all at once, instead of doing it manually for each pod.

**Comment by floreks** [comment] 2020-06-07 17:55
Duplicate of https://github.com/kubernetes/dashboard/issues/1016

/close

**Closed** 2020-06-07 17:55 UTC
Labels: kind/feature
