### ISSUE TITLE
EncryptionKeyHolderNamespace is hardcoded to kube-system, causes crash if dashboard is deployed to another namespace

### ISSUE THREAD

**Issue by ReillyProcentive** [kubernetes/dashboard#2770] opened 2018-01-16 00:47 UTC
##### Environment

```
Dashboard version: 1.8.2
Kubernetes version: 1.8.6 w/ RBAC
Operating system: CoreOS 1576
```

##### Steps to reproduce

1. Download the [k8s template](https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml)
2. Replace all instances of `namespace: kube-system` with a different namespace. We are using `k8s-dashboard`
3. Create all of the dashboard resources.

##### Observed result
The dashboard tries to create the `kubernetes-dashboard-key-holder` secret in the kube-system namespace. As it does not have permission to do so it panics and crashes.

```2018/01/16 00:17:43 Successful initial request to the apiserver, version: v1.8.6
2018/01/16 00:17:43 Generating JWE encryption key
2018/01/16 00:17:43 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/01/16 00:17:43 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/01/16 00:17:43 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: unexpected object: &Secret{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Data:map[string][]byte{},Type:,StringData:map[string]string{},}
2018/01/16 00:17:43 Storing encryption key in a secret
panic: secrets is forbidden: User "system:serviceaccount:k8s-dashboard:kubernetes-dashboard" cannot create secrets in the namespace "kube-system"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc420446e20)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:131 +0x2d3
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.NewRSAKeyHolder(0x1a7de00, 0xc4204209c0, 0xc4204209c0, 0x127b842)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:170 +0x83
main.initAuthManager(0x1a7d300, 0xc4202997a0, 0xc42054bde8, 0x1)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:166 +0x12f
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:100 +0x28c
/home/reilly/Projects/k8s-tevera-xyz/k8s-dashboard/dashboard.yaml
```

##### Expected result
The dashboard process should try to create the initial secret in the same namespace as the dashboard itself, OR it should allow us to specify which namespace to put the secret through an argument.

##### Comments
We are separating all third-party cluster components into their own individual namespaces in order to keep kube-system to only core system components (IE, what is created by kops upon creating/updating the cluster). This helps with kops as kops checks the health of kube-system pods as part of its cluster validation and also reduces the risk of critical k8s services being deleted by mistake.

**Comment by floreks** [comment] 2018-01-16 08:50
Duplicate of https://github.com/kubernetes/dashboard/issues/2655.

**Closed by floreks** 2018-01-16 08:50 UTC
