### ISSUE TITLE
https:kubernetes-dashboard:/proxy/api/v1/settings/pinner 401 (Unauthorized)

### ISSUE THREAD

**Issue by smarkm** [kubernetes/dashboard#4556] opened 2019-11-16 11:50 UTC
##### Environment

```
Installation method: kubectl apply -f URL
Kubernetes version: v1.16.2
Dashboard version: v2.0.0-beta4, v2.0.0-beta6
Operating system: Ubuntu server 18.04 
Node.js version: 8.10.0
Go version: Go 1.13
```

##### Steps to reproduce

1. kubectl apply -f URL
2.  Create sample user  https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
3. `sudo kubectl proxy --address 0.0.0.0 --port 80 --accept-hosts='.*'`
4. Use same LAN host with `${master-ip}`  access http://${master-ip}/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login

##### Observed result

1. polyfills.88f1732a940ff06121a3.js:1 GET 
http://172.16.2.101/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/api/v1/settings/pinner 401 (Unauthorized)
2. Can not Sign In with Token(`Sign in` not response)

##### Expected result

Successful Sign In

**Comment by floreks** [comment] 2019-11-16 17:24
Duplicate of #4537 

/close

**Closed by floreks** 2019-11-16 17:24 UTC
Labels: kind/bug
