### ISSUE TITLE
Kubernetes Dashboard reported Unknown Server Error

### ISSUE THREAD

**Issue by raghu67** [kubernetes/dashboard#1955] opened 2017-05-15 17:50 UTC
##### Steps to reproduce
1. Deployed a Kubernetes Cluster in AWS using kops 1.6.0 Beta 1
2. Deployed Heapster Addon
3. Deployed Dashboard Addon
4. Tried to access the Dashboard through https://<apiserver>/ui shortcut

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Unknown Server Error (403):
```
User "system:serviceaccount:kube-system:default" cannot list replicasets.extensions in the namespace "default". (get replicasets.extensions)
```

**Comment by floreks** [comment] 2017-05-15 19:56
Duplicate of at least #1800. Follow official readme md in order to deploy dashboard.

**Closed by floreks** 2017-05-15 19:56 UTC
Labels: cluster-issue, duplicate
