### ISSUE TITLE
Dashboard Settings CM name is hardcoded

### ISSUE THREAD

**Issue by vishaltak** [kubernetes/dashboard#5531] opened 2020-09-10 12:16 UTC
##### Environment
The ConfigMap used to store the dashboard settings is hardcoded [here](https://github.com/kubernetes/dashboard/blob/a1578e8bf496ae4c0a09979a9eaaa2497e8b38be/src/app/backend/settings/api/types.go#L27). When we install the kubernetes-dashboard as part of another helm chart(say, utility), the CM that is created is `utility-kubernetes-dashboard-settings`. Since, the backend of the dashboard is expecting the CM to be `kubernetes-dashboard-settings`, the configurable settings added in https://github.com/kubernetes/dashboard/pull/5508 are thus not realized. Any changes in the dashboard settings form the UI, creates a new CM `kubernetes-dashboard-settings`.

```
Installation method: Helm 3.1.0
Kubernetes version: 1.15.10
Dashboard version: 2.0.3
```

##### Steps to reproduce
1. Install Helm chart called "utility" which has kubernetes-dashboard as a dependency.
2. Change settings from the UI

##### Observed result
New CM `kubernetes-dashboard-settings` is created to store the custom settings

##### Expected result
Existing CM `utility-kubernetes-dashboard-settings` should be used to load the settings and should be the CM where the settings are updated

##### Comments
Solution - To fetch the CM name dynamically.

**Comment by floreks** [comment] 2020-09-10 12:56
This is basically a duplicate of https://github.com/kubernetes/dashboard/issues/4134 and it is definitely not a bug. All related resource names are fixed. We'd have to find a generic way to provide them. Adding flag per resource is not an option here. I am closing this one as if #4134 will be done, it will allow changing all resource names.

/close

**Closed** 2020-09-10 12:57 UTC
Labels: kind/bug
