### ISSUE TITLE
1.6.1 dashboard 4.3 error

### ISSUE THREAD

**Issue by byouloh** [kubernetes/dashboard#1819] opened 2017-04-05 09:08 UTC
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list replicasets.extensions in the namespace "default". (get replicasets.extensions)
```

**Comment by floreks** [comment] 2017-04-05 09:22
Duplicate of #1800. Related to #1803.

**Closed by floreks** 2017-04-05 09:22 UTC
