### ISSUE TITLE
Pie chart colors are all black with Korean / Japanese language setting.

### ISSUE THREAD

**Issue by haje01** [kubernetes/dashboard#7523] opened 2022-11-10 02:32 UTC
### What happened?

All chart colors are black regardless of the workload status.

### What did you expect to happen?

Pie charts show proper colors to express workload status

### How can we reproduce it (as minimally and precisely as possible)?

Go to Settings / Local settings,  change language as 'Korean' or 'Japanese'.
Then check pie chart colors.

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

Dashboard v2.7.0+0.g42deb6b32

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

### Dev environment

N/A

**Comment by maciaszczykm** [comment] 2022-11-14 08:48
Closing as duplicate of #7515.

**Closed by maciaszczykm** 2022-11-14 08:48 UTC
Labels: kind/bug
