### ISSUE TITLE
kong don't start

### ISSUE THREAD

**Issue by kinoher** [kubernetes/dashboard#8846] opened 2024-03-30 18:33 UTC
### What happened?

after fresh install from helm in readme.md file
all work except kong
```
kubectl -n kubernetes-dashboard logs kubernetes-dashboard-kong-7f67dfd776-xd5qr
Defaulted container "proxy" out of: proxy, clear-stale-pid (init)
Error: could not prepare Kong prefix at /kong_prefix: nginx configuration is invalid (exit code 1):
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /kong_prefix/nginx.conf:7
nginx: the configuration file /kong_prefix/nginx.conf syntax is ok
nginx: [emerg] bind() to [::1]:8444 failed (99: Cannot assign requested address)
nginx: configuration file /kong_prefix/nginx.conf test failed


  Run with --v (verbose) or --vv (debug) for more details
```                                                                                                          
  kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443
  https://localhost:8443 request login and password

### What did you expect to happen?

normal working

### How can we reproduce it (as minimally and precisely as possible)?

deploy oke basic cluster setup kubectl and exec helm command from readme

### Anything else we need to know?

i try version from 7.0.0 to 7.1.3

### Kubernetes Dashboard version

7.1

### Kubernetes version

Client Version: v1.29.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.28.2

**Comment by floreks** [comment] 2024-03-30 21:05
Duplicate of #8765

/close

**Closed by floreks** 2024-03-30 21:05 UTC
Labels: kind/bug
