### ISSUE TITLE
No Performance Graphs with 1.6.2

### ISSUE THREAD

**Issue by discostur** [kubernetes/dashboard#2198] opened 2017-07-27 15:40 UTC
```
Dashboard version: 1.6.2
Kubernetes version: 1.7.2
Operating system: CentOS 7.3
```

##### Steps to reproduce
Update Dashboard from 1.6.1 to 1.6.2

##### Observed result
No Performance (CPU / Memory usage) graphs are shown

If i downgrade to 1.6.1 graphs are showing up again; Seems to be a problem related to 1.6.2 ...

**Comment by floreks** [comment] 2017-07-27 15:48
Duplicate of #2180. I've provided temporary solution there.

**Closed by floreks** 2017-07-27 15:48 UTC

**Comment by discostur** [comment] 2017-07-27 16:41
Thx:)


Am 27.07.2017 um 17:49 schrieb Sebastian Florek <notifications@github.com<mailto:notifications@github.com>>:


Duplicate of #2180<https://github.com/kubernetes/dashboard/issues/2180>. I've provided temporary solution there.

-
