### ISSUE TITLE
There is a difference between kubectl output and dashboard for deployment detail.

### ISSUE THREAD

**Issue by f-higashi** [kubernetes/dashboard#885] opened 2016-06-13 07:47 UTC
#### Issue details

OldReplicaSets and newReplicaset value is difference between kubectl output and dashboard.

I created deployment.
```
$ kubect run nginx --image nginx
deployment "nginx" created
```

In the case of kubectl
```
$ kubectl describe deployments nginx
Name:                   nginx
Namespace:              default
CreationTimestamp:      Mon, 13 Jun 2016 16:09:54 +0900
Labels:                 run=nginx
Selector:               run=nginx
Replicas:               1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
OldReplicaSets:         <none>
NewReplicaSet:          nginx-2040093540 (1/1 replicas created)
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  6s            6s              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set nginx-2040093540 to 1
```

In dashboard
NewReplicaSet is not shown.
Old replicaSets is shown and contains replicaset which is  NewReplicaSet in kubectl.

![deployments](https://cloud.githubusercontent.com/assets/8746742/16000026/8bf7ea30-3184-11e6-8370-fedcfb5bfcbb.PNG)

##### Environment

```
Dashboard version: master d47a7b2b116f9f40c3efaf7fab764c000bb82d95
Kubernetes version: v1.2.4
kubectl client version: v1.2.4
Operating system: ubuntu 14.0.4
Node.js version: v5.1.1
Go version: 1.5.2
```

**Comment by bryk** [comment] 2016-06-13 08:45
@floreks @maciaszczykm I confirm this. Can one of you take the issue?

**Comment by floreks** [comment] 2016-06-13 08:57
I will check this.

**Comment by floreks** [comment] 2016-06-13 09:21
@bryk did you test it on k8s 1.3 or also 1.2.4?

On 1.3 I don't have this issue. After creating deployment deployments detail page matches kubectl describe.

![zrzut ekranu z 2016-06-13 11-20-01](https://cloud.githubusercontent.com/assets/2285385/16002585/d52206ae-3158-11e6-9ed5-214566662c58.png)

![zrzut ekranu z 2016-06-13 11-20-09](https://cloud.githubusercontent.com/assets/2285385/16002588/d914cdc8-3158-11e6-95d7-eadd370799d3.png)

**Comment by bryk** [comment] 2016-06-13 09:36
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

**Comment by floreks** [comment] 2016-06-13 09:40
So this may be an issue with `1.2.4` cluster version. I'll check.

**Comment by floreks** [comment] 2016-06-13 13:23
The issue seems to be connected to some differences between `1.2.4` and `1.3` k8s.

I've investigated it and found out that different pod template hash is generated between versions in this method.
https://github.com/kubernetes/dashboard/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go#L216

`FindOldReplicaSets` and `FindNewReplicaSet` used in our backend to get matching replica sets are using it.

On `1.3.0` both rs template from the server and generated on our backend are the same.

```
Generated:
{{      0 {0001-01-01 00:00:00 +0000 UTC} <nil> <nil> map[pod-template-hash:3137573019 run:nginx] map[] [] []} {[] [] [{nginx nginx [] []  [] [] {map[] map[]} [] <nil> <nil> <nil> /dev/termination-log Always <nil> false false false}] Always 0xc82043d068 <nil> ClusterFirst map[]   0xc8202f9a00 []  }}
Server:
{{      0 {0001-01-01 00:00:00 +0000 UTC} <nil> <nil> map[pod-template-hash:3137573019 run:nginx] map[] [] []} {[] [] [{nginx nginx [] []  [] [] {map[] map[]} [] <nil> <nil> <nil> /dev/termination-log Always <nil> false false false}] Always 0xc820274b20 <nil> ClusterFirst map[]   0xc820157e80 []  }}
```

However when using `1.2.4` cluster they are different.

```
Generated:
{{      0 {0001-01-01 00:00:00 +0000 UTC} <nil> <nil> map[pod-template-hash:2040093540 run:nginx] map[] [] []} {[] [] [{nginx nginx [] []  [] [] {map[] map[]} [] <nil> <nil> <nil> /dev/termination-log Always <nil> false false false}] Always 0xc8201c2ed8 <nil> ClusterFirst map[]   0xc82024a300 []  }}
Server:
{{      0 {0001-01-01 00:00:00 +0000 UTC} <nil> <nil> map[run:nginx pod-template-hash:3137573019] map[] [] []} {[] [] [{nginx nginx [] []  [] [] {map[] map[]} [] <nil> <nil> <nil> /dev/termination-log Always <nil> false false false}] Always 0xc820289180 <nil> ClusterFirst map[]   0xc820480f00 []  }}
```

I'm not sure if this is a bug or some logic has changed on purpose. If it's not a bug then we should handle this case somehow, perhaps by not displaying old/new rs at all on older clusters.

Any suggestions/ideas? @bryk @maciaszczykm 

cc @kubernetes/deployment

**Comment by bgrant0607** [comment] 2016-06-13 15:18
@janetkuo and @pwittrock found a similar issue in an e2e test.

Why does the back end need to do FindNewReplicaSet?

**Comment by floreks** [comment] 2016-06-14 05:50
> Why does the back end need to do FindNewReplicaSet?

We want to provide output similar to `kubectl describe` and it displays old/new replica sets related to deployment. 

Kubectl describe uses `FindNewReplicaSet` transparently also in here:
https://github.com/kubernetes/dashboard/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/describe.go#L1929

Only difference is that `GetNewReplicaSet` gets replica sets from the server and then executes `FindNewReplicaSet`. We are getting them on our own and executing it directly.

**Comment by bryk** [comment] 2016-06-22 09:55
I think this can be closed. Right, @floreks ?

**Comment by floreks** [comment] 2016-06-22 10:45
Well issue still exists on `1.2.4` clusters but seems to be related to k8s issue. We can close it on our side.

**Closed** 2016-09-13 13:09 UTC
Labels: kind/bug, priority/P0
