### ISSUE TITLE
Feature request: an ability to open terminal on each pod from the dashboard

### ISSUE THREAD

**Issue by maty21** [kubernetes/dashboard#615] opened 2016-04-05 03:24 UTC
sometimes it is really hard to investigate where are the problems without accessing to the container with bash 

imo it will be very useful if the option  to open terminal from the dashboard  will be available like other dashboards such as fabric8 for example

tks

**Comment by floreks** [comment] 2016-04-05 05:45
Duplicate of #550. 

Please follow the discussion there. Bash/SSH/Exec is part of the design for new dashboard version.
https://github.com/kubernetes/dashboard/blob/master/docs/design/mockups/23-03-2016-scale-and-navigation/pod-details-page-ssh.png. 

Also we have open PR with discussion about new design. You are welcome to join: https://github.com/kubernetes/dashboard/pull/589

**Closed by floreks** 2016-04-05 05:45 UTC
