### ISSUE TITLE
dashboard 1.6,2 was crashed  when click the nodes on the web

### ISSUE THREAD

**Issue by Bobi-zhou** [kubernetes/dashboard#2189] opened 2017-07-26 23:56 UTC
**# this logs is:**

> Creating remote Heapster client for http://heapster.kube-system:80
> Successful initial request to heapster
> Getting application global configuration
> Application configuration {"serverTime":1501112958896}
> [2017-07-26T23:49:19Z] Incoming HTTP/1.1 GET /api/v1/rbac/status request from 10.244.1.0:56574: {}
> [2017-07-26T23:49:19Z] Incoming HTTP/1.1 GET /api/v1/thirdpartyresource request from 10.244.1.0:56575: {}
> Getting list of third party resources
> [2017-07-26T23:49:19Z] Outcoming response to 10.244.1.0:56574 with 200 status code
> [2017-07-26T23:49:19Z] Outcoming response to 10.244.1.0:56575 with 200 status code
> [2017-07-26T23:49:19Z] Incoming HTTP/1.1 GET /api/v1/service/default?filterBy=&itemsPerPage=15&page=1&sortBy=d,creationTimestamp request from 10.244.1.0:56576: {}
> Getting list of all services in the cluster
> [2017-07-26T23:49:19Z] Outcoming response to 10.244.1.0:56576 with 200 status code
> [2017-07-26T23:49:23Z] Incoming HTTP/1.1 GET /api/v1/namespace?filterBy=&itemsPerPage=15&namespace=&page=1&sortBy=d,creationTimestamp request from 10.244.1.0:56575: {}
> Getting list of namespaces
> [2017-07-26T23:49:23Z] Outcoming response to 10.244.1.0:56575 with 200 status code
> [2017-07-26T23:49:24Z] Incoming HTTP/1.1 GET /api/v1/node?filterBy=&itemsPerPage=15&namespace=&page=1&sortBy=d,creationTimestamp request from 10.244.1.0:56575: {}
> panic: runtime error: index out of range
> 
> goroutine 100 [running]:
> panic(0x1c6d8e0, 0xc420014070)
> 	/home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/panic.go:500 +0x1a1
> github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster.heapsterClient.ithResourceDownload.func1(0x2cc5e60, 0xc420460fa0, 0x1e95537, 0x4, 0x1e97a5e, 0x6, 0xc420010b80, 0x3, 0x4, 0xc420403560, ...)
> 	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster/client.go:171 +0x5a5
> created by github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster.heapsterClient.ithResourceDownload
> 	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster/client.go:177 +0x109

**Comment by floreks** [comment] 2017-07-27 05:43
Duplicate of #2187. We'll track from there.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-07-27 05:43 UTC
Labels: duplicate
