### ISSUE TITLE
Dashboard v.2.0.0-beta1 resets to default namespace

### ISSUE THREAD

**Issue by slavditore** [kubernetes/dashboard#4058] opened 2019-07-13 20:38 UTC
##### Environment

```
Installation method: kubectl apply -f "filename"
Kubernetes version: 1.15.0
Dashboard version: v.2.0.0-beta1
Operating system: Debian 9
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Choose needed namespace
2. Create/delete any resource (pod, deployment etc)

##### Observed result

Resource created, but namespace sets to 'default' always.
##### Expected result

Resource created, you stay in last namespace you chose

**Comment by dejwoo** [comment] 2019-07-15 09:47
Can confirm this bug is also present in
```
Kubernetes version:  1.14.3
Dashboard version: v2.0.0-beta1
```

Dashboard deployed by running
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml
```

**Steps to reproduce:**

1. Delete any resource in any namespace other than default

**Observed result**
Resource deleted, however Dashboard always redirects to default namespace upon confirming deletion

**Expected result**
Resource deleted, Dashboard UI stays at the current screen from where the resource was deleted (if applicable - pod detail should probably redirect to pods screen?)

**Comment by maciaszczykm** [comment] 2019-07-15 12:43
Thanks for reporting, we will take a look before next release.

**Comment by floreks** [comment] 2019-07-15 16:53
This is because history service has not been fully rewritten. The original issue is: https://github.com/kubernetes/dashboard/issues/3911

Closing in favor of https://github.com/kubernetes/dashboard/issues/3911

/close

**Closed by floreks** 2019-07-15 16:53 UTC
Labels: kind/bug
