### ISSUE TITLE
my kube-dashboard still have admin permission

### ISSUE THREAD

**Issue by chesterlai** [kubernetes/dashboard#2446] opened 2017-10-06 10:32 UTC
##### Environment
Dashboard version: v1.7.1
Kubernetes version: 1.6.4
Operating system: ubuntu 16.04

##### Steps to reproduce
I create from 
https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

##### Observed result
I get token from kubernetes-dashboard-token-xxxxx 
after login I still can delete the pod easily.

##### Expected result
The permission the same with which wiki describe
https://github.com/kubernetes/dashboard/wiki/Access-control

**Comment by floreks** [comment] 2017-10-06 10:35
Take a look at note in the beginning of https://github.com/kubernetes/dashboard/wiki/Installation#official-release

**Comment by floreks** [comment] 2017-10-06 10:36
Also duplicate of #2412

**Comment by chesterlai** [comment] 2017-10-06 10:49
I don't have any serviceaccount with kubernetes dashboard
could you advice?

kubectl get serviceaccount --all-namespaces 
NAMESPACE        NAME       SECRETS   AGE
awse             default    1         18d
default          default    1         46d
demo-namespace   default    1         37d
diamond          default    1         13d
dpi              default    1         13d
kube-public      default    1         46d
kube-system      default    1         46d
kube-system      heapster   1         46d
kube-system      kube-dns   1         46d
office           default    1         43d

**Comment by floreks** [comment] 2017-10-06 10:51
> make sure to delete **Cluster Role Binding** for kubernetes-dashboard Service Account...

**Comment by chesterlai** [comment] 2017-10-06 10:52
I don't have clusterolebinding

kubectl get clusterrolebinding |grep -i dash
chester_lai@ip-10-102-4-66:/etc/kubernetes/sys/kube-dashboard/kube-system$

**Comment by floreks** [comment] 2017-10-06 10:59
If `kubectl describe clusterrolebinding kubernetes-dashboard` does not return something like below then this means that token you have used to log in has privileges to delete pods.
```bash
Name:		kubernetes-dashboard
Labels:		k8s-app=kubernetes-dashboard
Annotations:	<none>
Role:
  Kind:	ClusterRole
  Name:	cluster-admin
Subjects:
  Kind			Name			Namespace
  ----			----			---------
  ServiceAccount	kubernetes-dashboard	kube-system
```

**Comment by chesterlai** [comment] 2017-10-06 11:07
Yes 
there is no  clusterrolebinding "kubernetes-dashboard"

chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl describe clusterrolebinding kubernetes-dashboard
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "kubernetes-dashboard" not found

That's why I open this issue
looks like the RBAC doesn't work, and the user still have admin permission.

Or correct me if I have any misunderstanding.
Many thanks

**Comment by chesterlai** [comment] 2017-10-06 11:09
there is no clusterrolebinding configuration in 
https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by floreks** [comment] 2017-10-06 11:11
There was one in `1.6`. That is why many people are forgetting about removing old dashboard version first before installing new one.

**Comment by chesterlai** [comment] 2017-10-06 11:12
But I don't have this permission.
I think my situation is different.

**Comment by chesterlai** [comment] 2017-10-06 11:13
as you can see , there is no clusterbinding with my kubernetes-dashboard-minimal

**Comment by floreks** [comment] 2017-10-06 11:15
I still think there is an issue on your side. Show me Service Account, Role, Role Binding and Cluster Role (if exists) related to the token you are using to log in.

**Comment by chesterlai** [comment] 2017-10-06 11:20
chester_lai@ip-10-102-4-66:~/kube_dashboard$ bectl get serviceaccount --all-namespaceskubectl get serviceaccount --all-namespaces^C
chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl get serviceaccount --all-namespaces|grep dash
kube-system      kubernetes-dashboard   1         14m
chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl get role --all-namespaces|grep dash
kube-system      kubernetes-dashboard-minimal                14m
chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl get rolebinding --all-namespaces|grep dash
kube-system      kubernetes-dashboard-minimal         14m
chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl get clusterrole|grep dash
chester_lai@ip-10-102-4-66:~/kube_dashboard$

**Comment by floreks** [comment] 2017-10-06 11:22
Describe it. I need to see privileges.

**Comment by chesterlai** [comment] 2017-10-06 11:25
kubectl describe serviceaccount --namespace=kube-system kubernetes-dashboard 
Name:           kubernetes-dashboard
Namespace:      kube-system
Labels:         k8s-app=kubernetes-dashboard
Annotations:    <none>

Image pull secrets:     <none>

Mountable secrets:      kubernetes-dashboard-token-9tt65

Tokens:                 kubernetes-dashboard-token-9tt65


kubectl describe  --namespace=kube-system role  kubernetes-dashboard-minimal 
Name:           kubernetes-dashboard-minimal
Namespace:      kube-system
Labels:         <none>
Events:         <none>

chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl describe  --namespace=kube-system rolebinding  kubernetes-dashboard-minimal 
Name:           kubernetes-dashboard-minimal
Namespace:      kube-system
Labels:         <none>
Events:         <none>

**Comment by maciaszczykm** [comment] 2017-10-06 11:27
Are you using Kubernetes Addon Manager? It is possible, that it restores specific resources after changing/removing them.

**Comment by floreks** [comment] 2017-10-06 11:28
This is how valid output should look like:
```
floreks@floreks-MS-7916:~$ kubectl -n kube-system describe rolebinding kubernetes-dashboard-minimal
Name:		kubernetes-dashboard-minimal
Labels:		<none>
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"RoleBinding","metadata":{"annotations":{},"name":"kubernetes-dashboard-minimal","namespace":"...
Role:
  Kind:	Role
  Name:	kubernetes-dashboard-minimal
Subjects:
  Kind			Name			Namespace
  ----			----			---------
  ServiceAccount	kubernetes-dashboard	kube-system

floreks@floreks-MS-7916:~$ kubectl -n kube-system describe role kubernetes-dashboard-minimalName:		kubernetes-dashboard-minimal
Labels:		<none>
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"Role","metadata":{"annotations":{},"name":"kubernetes-dashboard-minimal","namespace":"kube-sy...
PolicyRule:
  Resources	Non-Resource URLs	Resource Names				Verbs
  ---------	-----------------	--------------				-----
  secrets	[]			[]					[create watch]
  secrets	[]			[kubernetes-dashboard-certs]		[delete]
  secrets	[]			[kubernetes-dashboard-certs]		[get]
  secrets	[]			[kubernetes-dashboard-certs]		[update]
  secrets	[]			[kubernetes-dashboard-key-holder]	[delete]
  secrets	[]			[kubernetes-dashboard-key-holder]	[get]
  secrets	[]			[kubernetes-dashboard-key-holder]	[update]
  services	[]			[heapster]				[proxy]
```

If you do not have any privileges listed then probably RBACs are disabled in your cluster or the is some other issue with your cluster.

**Comment by chesterlai** [comment] 2017-10-06 11:33
I don't know why my output has no subject

chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl -n kube-system describe rolebinding kubernetes-dashboard-minimal
Name:           kubernetes-dashboard-minimal
Namespace:      kube-system
Labels:         <none>
Events:         <none>
chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl -n kube-system describe role kubernetes-dashboard-minimal
Name:           kubernetes-dashboard-minimal
Namespace:      kube-system
Labels:         <none>
Events:         <none>

I indeed enable RBAC, because if I use wrong token I can't login my system.

I have use RBAC for other application and it worked, too.
I have confirmed I enable RBAC in my kube-apiserver with below tag
    - --authorization-mode=RBAC

**Comment by floreks** [comment] 2017-10-06 11:35
Try to remove and recreate it. I'm not sure what could go wrong. Also it would be best to update kubernetes to v1.7+ also as we do not guarantee everything will work correctly on older versions.

**Comment by chesterlai** [comment] 2017-10-06 11:35
@ maciaszczykm   I don't know what do you mean 
could you describe more?
I think I don't install that kinds of pod

chester_lai@ip-10-102-4-66:~/kube_dashboard$ kubectl get pod --all-namespaces |grep -i add
chester_lai@ip-10-102-4-66:~/kube_dashboard$

**Comment by chesterlai** [comment] 2017-10-06 11:39
@floreks  
Yes
I have remove and recreate it
you can see the timeline which I paste just around 10~20 mins ago

Our kubernetes version is 1.6.4 with RBAC.
My problem is there is only admin permission for  dashboard 1.6.1
Have any suggestion for k8s 1.6.4?

And could you remove duplicate tag for this issue?
looks like this is indeed a issue for k8s 1.6.4

**Comment by chesterlai** [comment] 2017-10-06 11:42
thanks for reopen
any suggestion on k8s 1.6 dashboard is welcome

**Comment by floreks** [comment] 2017-10-06 11:46
Anyway this does not look like Dashboard issue since role privileges are empty. Even role binding does not say that given role is bound to `kubernetes-dashboard` service account. This definitely looks like some kind of cluster issue. I can't say for sure that this is a kubernetes bug. Might be configuration issue.

We can help in case of dashboard issues. If you will be able to create and correctly list role and role bindings with all privileges and still encounter this issue, then we can reopen that. Until that ask for help on core repository.

**Closed** 2017-10-06 11:47 UTC

**Comment by maciaszczykm** [comment] 2017-10-06 11:56
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager#addon-manager

https://kubernetes.io/docs/concepts/cluster-administration/addons/
