### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by davidxia** [kubernetes/dashboard#1973] opened 2017-05-18 17:43 UTC
##### Environment

```
Dashboard version:
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Operating system:
OS X 10.12.4 Sierra

Node.js version:

go version go1.8.1 darwin/amd64

```
##### Observed result
Dashboard reported Internal Server Error (500):
```
[restful] recover from panic situation: - Failed to create heapster selector for resource "deployment". Error: GetMyPodsFromCache: pods were not available in cache. Required for resource type: "deployment"
    /usr/lib/google-golang/src/runtime/asm_amd64.s:479
    /usr/lib/google-golang/src/runtime/panic.go:463
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:131
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:184
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/deployment/deploymentlist.go:115
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/deployment/deploymentlist.go:99
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/deployment/deploymentlist.go:67
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:928
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:266
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:267
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:21
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:85
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:19
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:269
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:120
    /usr/lib/google-golang/src/net/http/server.go:1726
    /usr/lib/google-golang/src/net/http/server.go:2022
    /usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:287
    /usr/lib/google-golang/src/net/http/server.go:2022
    /usr/lib/google-golang/src/net/http/server.go:2202
    /usr/lib/google-golang/src/net/http/server.go:1579
    /usr/lib/google-golang/src/runtime/asm_amd64.s:2086

```

**Comment by floreks** [comment] 2017-05-18 18:08
Duplicate of #1972

**Closed by floreks** 2017-05-18 18:08 UTC
