### ISSUE TITLE
Dashboard crashes with large number of pods in the cluster

### ISSUE THREAD

**Issue by tartavull** [kubernetes/dashboard#1711] opened 2017-03-10 14:12 UTC
##### Environment

It worked fine with 400 pods, but in crashes when using 1600 pods

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'EOF'
Trying to reach: 'http://10.0.7.5:9090/api/v1/workload/default?itemsPerPage=10&page=1'
```

**Comment by maciaszczykm** [comment] 2017-03-13 09:22
I've allowed myself to edit issue title.

**Comment by floreks** [comment] 2017-03-17 19:30
It looks like a duplicate of #1431. A short term solution might be extending memory limits for the dashboard. We'll have to look at this but the best solution is if kubernetes implements pagination on their side. There are some plans for that but no dates yet. 

Closing in favor of #1431. We will track it from there.

**Closed by floreks** 2017-03-17 19:30 UTC
Labels: area/performance, kind/bug, priority/P1
