### ISSUE TITLE
Dashboard v1.6.2 crash on pod exec

### ISSUE THREAD

**Issue by chyh1990** [kubernetes/dashboard#2203] opened 2017-07-28 09:09 UTC
##### Environment

```
Dashboard version: 1.6.2
Kubernetes version: 1.6.4
Operating system: CentOS 7.2
Node.js version:
Go version:
```

##### Steps to reproduce

1. `exec` into a pod
2. run any commands
3. press Ctrl+D, show `process exited`
4. dashboard crashes :-<

##### Observed result

dashboard crash with logs:

```
[2017-07-28T08:43:42Z] Outcoming response to 10.244.0.0:49530 with 200 status code
[2017-07-28T08:43:42Z] Incoming HTTP/1.1 GET /api/v1/pod/default/search-worker-1/container request from 10.244.0.0:49530: {}
[2017-07-28T08:43:42Z] Outcoming response to 10.244.0.0:49530 with 200 status code
[2017-07-28T08:43:43Z] Incoming HTTP/1.1 GET /api/v1/pod/default/search-worker-1/shell/search-worker request from 10.244.0.0:49530: {}
[2017-07-28T08:43:43Z] Outcoming response to 10.244.0.0:49530 with 200 status code
E0728 08:45:19.889043       1 v2.go:105] sockjs: session not in open state
E0728 08:45:19.889043       1 v2.go:105] sockjs: session not in open state
log: exiting because of error: log: cannot create log: open /tmp/dashboard.kubernetes-dashboard-1113981146-z9x0c.unknownuser.log.ERROR.20170728-084519.1: no such file or directory
```

##### Expected result

It does not crash.

**Comment by floreks** [comment] 2017-07-28 09:20
Are you trying to exec in dashboard pod?

**Comment by idealhack** [comment] 2017-07-28 10:08
I've seen this crash when exec into any pod using 1.6.2.

**Comment by floreks** [comment] 2017-07-28 11:08
See my https://github.com/kubernetes/dashboard/issues/2202#issuecomment-318624951. Unfortunately it is due to some breaking changes between 1.6 and 1.7 kubernetes. We'll try to deal with it. For now exec functionality works only on 1.6 clusters.

**Comment by floreks** [comment] 2017-08-03 12:21
Duplicate of #2190 as the underlying cause is the same.

**Closed by floreks** 2017-08-03 12:21 UTC
Labels: kind/bug, priority/P1
