### ISSUE TITLE
workload page stalls

### ISSUE THREAD

**Issue by therc** [kubernetes/dashboard#817] opened 2016-06-05 02:12 UTC
#### Issue details
The /#/workload page stalls. Chrome shows the request as still pending. Not even one byte is transferred.

##### Environment

```
Dashboard version: 1.1.0-beta2 (was also in beta1)
Kubernetes version: HEAD 1.3
Operating system: CoreOS on the server, Linux on the client
Node.js version: whatever is in the beta2 image
Go version: ditto
```

##### Steps to reproduce
Open the top level page

##### Observed result
Nothing happens for a long time. The tab is unresponsive and needs to be killed. Eventually, there's a timeout (my dashboard is behind AWS ELB, that might be causing it).

##### Expected result
The workload page loads.

##### Comments
I suspect the problem is that one or more channels from 
https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/workload/workloads.go#L54

stalls. I can actually load the rc, rs, ds, deployment, petset, service and pod endpoints. So maybe it's one of joblist, eventlist or nodelist.

The real problem is that there is

1. no logging or useful diagnostics
1. apparently, no timeout

**Comment by floreks** [comment] 2016-06-06 06:54
> no logging or useful diagnostics
This have happened after some update and `log` is not working. I'll investigate that and restore logging.

> apparently, no timeout
Yes, we need some timeout for channels when there is no response from kubernetes because now it hangs completely when no data is received.

**Comment by floreks** [comment] 2016-06-06 09:08
Few questions to help me reproduce the problem.

How big is your cluster? Number of controllers/Pods/Events?
How long does it take to run `kubectl get events --all-namespaces`

Could you provide some test yaml(s) so I can prepare same structure?

**Comment by therc** [comment] 2016-06-06 14:42
There are currently 10 nodes (three of which are masters) and about 70 pods.

Only three events show up, so it's instantaneous. That number looks suspiciously low, though. The worst is `get rs`, but even that takes only one second. There are 2680 replicasets, most of them empty, because we are not setting history limits yet. Could that be the problem?

**Comment by therc** [comment] 2016-06-06 14:48
I deleted and recreated a DaemonSet. There are more than 70 events now and kubectl took 0.036s to show them.

**Comment by therc** [comment] 2016-06-06 15:35
I trimmed deployment revision history. We're already down to 516 replicasets, but the workload page still needs to be killed. `/#/replicaset?namespace=kube-system` works, but it only has six items. I hadn't tried the other namespaces, but it looks like loading the replicasets for the other namespaces takes a large amount of time, proportional to the number of items. They eventually load, if I ignore Chrome's prompt to kill the tab.

It should be noted that by default `revisionHistoryLimit` is unbound in a Deployment, so this will probably start hitting a lot of people.

This is the current split of replicasets among namespaces:

```
     59 dev        
      6 kube-system
    166 prod       
    285 staging    
```

**Comment by therc** [comment] 2016-06-06 15:42
With 166 replicasets:
```
$ time kubectl get rs --namespace=prod
[...]
real	0m0.105s
[...]
$ time kubectl describe rs --namespace=prod
[...]
real	1m4.424s
[...]
```

**Comment by floreks** [comment] 2016-06-06 18:29
That helps alot thanks. For now we'll prepare frontend pagination as this seems to be rendering issue.  Hopefully it will be ready for next beta release so you can test.

**Comment by therc** [comment] 2016-06-06 23:13
Is pagination really the solution? I now have a history of 10 replicasets for each deployment. That means that only one of eleven replicasets has useful information. What I need might be on page 2, 3 or 4.
Would it be better to do the equivalent of a kubectl get (which is fast), followed by a kubectl describe only for the replicasets  where `desired` or `current` are not zero? The idle/old replicasets would show less information, but you can still click on each of them to get more details.

**Comment by floreks** [comment] 2016-06-07 06:45
Lists contain more information then what `kubectl get` provides. We are also getting related events in order to show the status of resource and possibly error messages. Anyway in any case where there will be many resources on the list to render it will crash. It is not caused by the time we need to get the actual information but by the angular material which is unable to render that much information on one page.

For example: 500 pods, list page. To get data we need like ~8s but still page won't render because frontend will crash. Only way is to split this data and render 10/25/50 resources and add pagination option.

**Comment by bryk** [comment] 2016-06-07 07:18
@therc And one more thing. Typically, the dashboard UI backend is close to the apiserver. So we're not worried about transferring large amounts of data between them. But then, browsers can render only small amount of data at a time. That's why we need pagination or infini scroll

**Comment by therc** [comment] 2016-06-07 16:00
Well, what I was trying to say is that I'm OK if old replicasets get simplified rendering (e.g. without labels, without image information, maybe even without events). For me, in the workload list or even in the replicasetlist page, historical items don't need more information than what `kubelctl get` provides. Most of the time I really care only about the ones that are actually running. That should make the generated HTML smaller and cause the browser to spend less time on layouting.

If you have to paginate, please consider moving historical items to the graveyard, i.e. pages other than the first (in other words, don't just sort A->Z).

**Comment by bryk** [comment] 2016-06-08 07:15
> If you have to paginate, please consider moving historical items to the graveyard, i.e. pages other than the first (in other words, don't just sort A->Z).

What is best ordering for you? Creation date? Name?

**Comment by therc** [comment] 2016-06-08 12:56
I think replica sets need custom ordering, because of the way they are created and managed by deployments.

To give you an example, assume that I have three deployments, A, B and C, that I learned the lesson and that I set `revisionHistoryLimit` to 3. This means I'll eventually have four replica sets for each (current rollout, plus history of three).

The rollouts happen with different schedules. For convenience, let's refer to the replica sets with {DEPLOYMENT}{AGE_IN_DAYS}. So I have A0, A7, A14, A21, B9, B19, B29, B39, C1, C3, C5, C7.
The only ones to have any running pods are A0, B9, C1, unless there's a rolling update in progress. So the best ordering might be those three (sorted by date, preferably, so that during an update the 'fresh' replica set shows first, or otherwise name), followed by all the other empty replica sets. If I merely sorted by age, I would have useless replicasets like C3, C5, C7 and A7 showing up before B9. Even worse if I sorted by name. The inconvenience only gets worse when the number of deployments or the history size are large (I have 10 for the latter). Or when users don't set any history limits at all.

I would make the case that the empty replica sets should actually be ghosted, show fewer details and/or be hidden by default. Also, like Borg, it would be nice to highlight a RS or RC that is undergoing updates.

cc @bgrant0607

**Comment by bryk** [comment] 2016-06-10 11:20
> I think replica sets need custom ordering, because of the way they are created and managed by deployments.

> To give you an example, assume that I have three deployments, A, B and C, that I learned the lesson and that I set revisionHistoryLimit to 3. This means I'll eventually have four replica sets for each (current rollout, plus history of three).

> The rollouts happen with different schedules. For convenience, let's refer to the replica sets with {DEPLOYMENT}{AGE_IN_DAYS}. So I have A0, A7, A14, A21, B9, B19, B29, B39, C1, C3, C5, C7.
The only ones to have any running pods are A0, B9, C1, unless there's a rolling update in progress. So the best ordering might be those three (sorted by date, preferably, so that during an update the 'fresh' replica set shows first, or otherwise name), followed by all the other empty replica sets. If I merely sorted by age, I would have useless replicasets like C3, C5, C7 and A7 showing up before B9. Even worse if I sorted by name. The inconvenience only gets worse when the number of deployments or the history size are large (I have 10 for the latter). Or when users don't set any history limits at all.

> I would make the case that the empty replica sets should actually be ghosted, show fewer details and/or be hidden by default. Also, like Borg, it would be nice to highlight a RS or RC that is undergoing updates.

Thanks @therc for this feedback. I agree with most statements here. Our plans were to order by "importance". I.e., put errored resources or things that need attention at the top. We'll do this however in next release, since we don't have capacity to squeeze it for this one. I hope that next releases will be more frequent. Like, monthly.

**Comment by bryk** [comment] 2016-06-10 11:21
We'll be improving the page, but the problem reported here fixed. Closing :)

**Closed by bryk** 2016-06-10 11:21 UTC

**Comment by therc** [comment] 2016-06-10 12:33
Thanks. I'll open a separate issue for the remaining work. Is a new beta getting released today? There have been major improvements and I'd be happy to test them all (on AWS).

**Comment by edouardKaiser** [comment] 2016-06-10 12:38
Can't wait to test a new beta too, lots of useful features have been merged !

**Comment by floreks** [comment] 2016-06-10 12:42
Yep, next beta should be released today. I'd like to get #872 and #874 merged before release.

**Comment by bgrant0607** [comment] 2016-06-10 14:08
@therc Good ideas.

cc @kubernetes/deployment
