### ISSUE TITLE
Memory chart keeps resizing

### ISSUE THREAD

**Issue by Eddman** [kubernetes/dashboard#5314] opened 2020-06-26 10:09 UTC
##### Environment

```
Installation method: kubeadm + Helm
Kubernetes version: 1.16.9
Dashboard version: 2.0.3
Operating system: N/A
Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A
```

##### Steps to reproduce
When the page is resized to a particular size the memory chart starts to resize indefinitely and it is "dancing" :man_dancing:/re-rendering in a loop. Don't know how to describe it better. It's very hard to reproduce and even I'm only able to see it on my Lenovo X1 Tablet in Chrome stretched to full screen. Even a slight width change returns the chart to normal. Also it is happening in the big upper "Memory" chart only. CPU chart is not affected.

##### Observed result
Memory chart keeps resizing.

##### Expected result
Memory chart resizes to correct size once and stays.

**Comment by floreks** [comment] 2020-06-26 10:12
Duplicate of #5106 and more #5050 and more.

/close

**Closed** 2020-06-26 10:13 UTC
Labels: kind/bug

**Comment by Eddman** [comment] 2020-06-26 10:19
@floreks Both are closed and the issue still persists in the latest version. Do you really want to close it just like that :slightly_smiling_face:?

**Comment by floreks** [comment] 2020-06-26 10:45
@Eddman read the comments in https://github.com/kubernetes/dashboard/issues/5050. This is an external library issue. There is nothing we can do about that. There is no good workaround here.

**Comment by Eddman** [comment] 2020-06-26 11:40
I get that, but still, closing an issue that still persists seems wrong to me. You should either keep at least one issue open, or go with some other library where you'll not have this issue. Closing it saying "it is not here" as if it does not exist in the Dashboard seems really wrong to me.

PS. I did go through all opened issues before I opened this one. I guess many more will do the same....

**Comment by floreks** [comment] 2020-06-26 12:10
Like I have mentioned in the first issue. Dependency bot will automatically fix this in case it gets fixed by the library maintainers. We have already tried 3 different chart libraries before this one and all of them were buggy. Keeping it open means that we can do something about it and someone on our side could fix this. Since this is not the case and this can be automatically fixed by dependency bot I don't see a reason to keep it open for unknown period of time.
