### ISSUE TITLE
500 error  when use dashboard 

### ISSUE THREAD

**Issue by mysterytree** [kubernetes/dashboard#415] opened 2016-02-23 09:51 UTC
![image](https://cloud.githubusercontent.com/assets/6166794/13247619/8033f7b0-da55-11e5-8c4e-88019e7bd839.png)
![image](https://cloud.githubusercontent.com/assets/6166794/13247623/884025dc-da55-11e5-82f8-6941ef563129.png)

and the rc.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kubedash
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard 
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard:canary
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 5
```
service:
```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kubernetes-dashboard 
  ports:
  - port: 50071
    targetPort: 9090
  type: LoadBalancer
  externalIPs:
  -  10.4.5.62
```

**Comment by floreks** [comment] 2016-02-23 09:58
This will be fixed in #412. The problem is that our build pipeline has changed and now we have images for different architectures.

You should actually use `image: gcr.io/google_containers/kubernetes-dashboard-amd64:canary` or just try yaml file from above PR.

**Comment by mysterytree** [comment] 2016-02-23 10:03
Thanks a lot !!!

**Comment by mysterytree** [comment] 2016-02-23 10:13
@floreks 
![image](https://cloud.githubusercontent.com/assets/6166794/13248354/c38c5b94-da58-11e5-8382-4329bfe582ee.png)

k8s on mesos , the api - server params needed?

**Comment by floreks** [comment] 2016-02-23 10:15
You shouldn't worry about that when you deploy from yaml. In-cluster config will be used.

**Comment by bryk** [comment] 2016-02-23 10:36
I'll cut a release today and you'll be able to test it. I'll let you know.

**Comment by bryk** [comment] 2016-02-23 13:49
Released, canary images pushed: https://github.com/kubernetes/dashboard/releases/tag/v1.0.0-beta1

**Comment by mysterytree** [comment] 2016-02-24 03:47
Test the gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.0-beta1 
![image](https://cloud.githubusercontent.com/assets/6166794/13274966/c66875ea-daea-11e5-8109-f13af3a6b2a7.png)
![image](https://cloud.githubusercontent.com/assets/6166794/13275067/0ca2282a-daec-11e5-8948-66c45464abdf.png)

**Comment by mysterytree** [comment] 2016-02-24 04:24
fix with 
```
 args:
        - --port=9090
        - --apiserver-host=10.4.14.85:8888
        command:
        - /dashboard
        - --port=9090
        - --apiserver-host=10.4.14.85:8888
```

**Comment by mysterytree** [comment] 2016-02-24 04:24
fix with 
```
 args:
        - --port=9090
        - --apiserver-host=10.4.14.85:8888
        command:
        - /dashboard
        - --port=9090
        - --apiserver-host=10.4.14.85:8888
```

**Comment by mysterytree** [comment] 2016-02-24 04:26
@bryk 
api-server port is 8888 in k8s on meos
and the some args needed

**Comment by bryk** [comment] 2016-02-24 08:02
@mysterytree 

The backend should do auto discovery of master when running inside a cluster. Can you help us with debugging this? 

1. Does your cluster have service accounts?
2. Can you set up a demo cluster for us so that we can debug live on it?

**Comment by mysterytree** [comment] 2016-02-26 01:41
Thanks for your help ,  the dashboard run in the production environment and can't set up demo cluster for you ....  I'm so sorry about it .But  it is my pleasure to cooperate with you.   I would l monitor the dashboard  later in production environment and found more questions for you .

**Comment by bryk** [comment] 2016-03-04 13:41
Closing as stale. Reopen if needed.

**Closed by bryk** 2016-03-04 13:41 UTC
