### ISSUE TITLE
Dashboard 1.6.3 crashes frequently on kube 1.7.2

### ISSUE THREAD

**Issue by bcorijn** [kubernetes/dashboard#2230] opened 2017-08-03 12:17 UTC
##### Steps to reproduce

Updated my cluster to 1.7.2 and my dashboard to 1.6.3, just browsing around the dashboard I can get it to crash very easily, with the below error reported. Container logs don't tell much more..

##### Environment
```
Installation method: cluster through kops + manually switched the dashboard to v1.6.3
Kubernetes version: v1.7.2
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'dial tcp 100.96.13.5:9090: getsockopt: connection refused'
Trying to reach: 'http://100.96.13.5:9090/api/v1/pod/kube-system/kubernetes-dashboard-220506704-9t4cf'
```
After this the container restarts.

##### Comments

First time I had it when browsing logs, after which I could see this in the container logs:
```
[2017-08-03T10:55:41Z] Incoming HTTP/1.1 GET /api/v1/pod/test/pagefetcher-test-3032599838-k11nb/shell/pagefetcher request from 10.10.86.138:42806: {}
[2017-08-03T10:55:41Z] Outcoming response to 10.10.86.138:42806 with 200 status code
E0803 10:55:43.327188       1 v3.go:79] EOF
E0803 10:55:43.327188       1 v3.go:79] EOF
log: exiting because of error: log: cannot create log: open /tmp/dashboard.kubernetes-dashboard-220506704-9t4cf.unknownuser.log.ERROR.20170803-105543.1: no such file or directory
```
Other times it was while browsing to the dashboard pod itself, with no error:
```
Getting pod metrics
[2017-08-03T11:02:33Z] Outcoming response to 10.10.86.138:43194 with 200 status code
[2017-08-03T11:02:36Z] Incoming HTTP/1.1 GET /api/v1/pod/kube-system?filterBy=&itemsPerPage=15&page=1&sortBy=d%!C(MISSING)creationTimestamp request from 10.10.86.138:43194: {}
Getting list of all pods in the cluster
Getting pod metrics
[2017-08-03T11:02:37Z] Outcoming response to 10.10.86.138:43194 with 200 status code
[2017-08-03T11:02:41Z] Incoming HTTP/1.1 GET /api/v1/pod/kube-system/kubernetes-dashboard-220506704-9t4cf request from 10.10.86.138:43194: {}
Getting details of kubernetes-dashboard-220506704-9t4cf pod in kube-system namespace
```

**Comment by floreks** [comment] 2017-08-03 12:19
`/api/v1/pod/test/pagefetcher-test-3032599838-k11nb/shell/pagefetcher`

Exec into pod is in an early stage. It's known not to be working properly with kubernetes 1.7.

**Comment by floreks** [comment] 2017-08-03 12:22
Duplicate of #2190 as the underlying case is the same.

**Comment by bcorijn** [comment] 2017-08-03 12:23
@floreks I did not open the exec tab however on the last few crashes?

**Comment by floreks** [comment] 2017-08-03 12:28
Dashboard `1.6` is using `client-go` compatible with K8S `1.6` and we can not guarantee that it will be stable with newer versions. There are just too many changes between versions. Only our HEAD image has been migrated to `1.7` right now. We can only guarantee that dashboard will be working correctly with major version of K8S equal to dashboard.

**Comment by floreks** [comment] 2017-08-03 12:31
You could also `kubectl describe` dashboard pod when it crashes. Sometimes you may find there some more information like reason why container crashed/was killed.  Try to increase memory limits maybe it is crashing with `OOMKilled`.

**Closed** 2017-08-03 17:17 UTC
Labels: duplicate
