### ISSUE TITLE
Some waiting pods have incorrect icons

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1349] opened 2016-10-20 08:51 UTC
I recently checked my dev cluster and saw this: 
![selection_135](https://cloud.githubusercontent.com/assets/1159999/19553074/ee74d1b2-96b2-11e6-8211-f9fe439fe1f5.png)

Everything is green or gray, but it should not be. Pods prefixed with `ewa-app-` should have red icon. The `maxmaxmax...` one should be potentially red and `mysql` perhaps too. 

cc @IanLewis @rf232

**Comment by floreks** [comment] 2016-10-20 09:00
This is similar to #1121. Origin of this issue is the same, because pod is considered running/waiting by the kubernetes itself and containers are failing. Right now icon reflects only pod state not pod with containers and this should be changed.

Additionally on pods page we don't handle events and our error recognition is based on them.

**Comment by IanLewis** [comment] 2016-10-20 09:00
The icon is still looking at the pod state currently and it's "Running" for
those with pods in a crash loop.

I explicitly left changing this behavior out of my last change as it needed
some discussion. We need to define what situations should show red icons vs
green. I think we may need a yellow too for initializing pods, pods with
containers waiting for an image pull etc.

I'm willing to take this on as it's relatively simple change. The hard part
is deciding on design

**Comment by IanLewis** [comment] 2016-10-20 09:03
I think we can close #1121 as addressed by my earlier changes and use this issue for discussion of the icon.

**Comment by bryk** [comment] 2016-10-21 08:06
If I was to propose the algorithm, I'd say:
1. Only pods with status equal to "Running" have green icon.
2. "Waiting" status may be red or grey. I'd go through all waiting reasons and make categorize them using common sense. If a reason ends with "BackOff", I'd make it red. 

What do you think?

**Comment by rf232** [comment] 2016-10-21 14:03
Sounds like a nice algorithm

**Comment by IanLewis** [comment] 2016-10-23 06:25
For reference, here are the definitions of some errors we need to care about:

https://github.com/kubernetes/kubernetes/blob/4f32cc073b68850979e648996df0b09cd11a2263/pkg/kubelet/images/types.go
https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/kubelet/container/sync_result.go

**Comment by IanLewis** [comment] 2016-10-24 03:04
Should we use things like the pod conditions (Initialized, Ready) for this. I'm wary of using the status string as we display it here to run the algorithm.

**Comment by bryk** [comment] 2016-10-24 10:00
> Should we use things like the pod conditions (Initialized, Ready) for this. I'm wary of using the status string as we display it here to run the algorithm.

Yes, I proposed the algorithm from the end user perspective. Implementation may (and should) base on status fields. 

> For reference, here are the definitions of some errors we need to care about:

Looks like a thing we should be using for this. Thanks!

**Comment by IanLewis** [comment] 2016-10-25 05:11
@bryk Can you assign this to me?

**Comment by IanLewis** [comment] 2016-11-22 09:05
My thought is that we should check the pod's status.conditions to see if it's Ready to see if we show an error icon or not.

Status Pending = Grey icon
Status Running, Not Ready = Red icon
Status Running, Ready = Green icon

This will show it as in an error state if it is failing a readinessProbe but maybe that actually what we want?

**Comment by floreks** [comment] 2016-11-22 11:50
I'm working on that actually. Almost finished. I've added support for events on pod list so error icon will be shown when there is an error event or pod is in failed state.

**Comment by IanLewis** [comment] 2016-11-22 13:38
Ok. I was starting work on this but I'll defer to you then. I'd like to review it so let me know when it's finished :)

**Comment by floreks** [comment] 2016-11-22 13:50
You can check this out now :) #1467

**Comment by IanLewis** [comment] 2016-11-30 08:28
@floreks I looked at #1467. It looks like you set up the functionality for showing events but aren't actually getting them yet?

**Comment by IanLewis** [comment] 2016-11-30 09:03
My idea was closer to this: #1502. This PR looks at the pod conditions for the readiness state and shows an error icon if the pod is not ready. I think it could be used in combination with your solution.

**Comment by floreks** [comment] 2016-11-30 09:21
@IanLewis events for particular pod are taken from k8s. If there is any issue with the pod and it is not ready or failed then there will be an error/warning event indicating what's wrong. Have you found some cases where pod is in error state and icon stays pending after my update? It should work now, same as on other resource pages.

**Comment by IanLewis** [comment] 2016-11-30 10:24
@floreks I suppose you're right but it looks like you are setting the status based on whether there are error/warning messages rather than showing the error/warning messages if the pod is in an error state. One issue I have with using events as a status indicator is how does the dashboard know when the pod has returned to a non-error state and should go back to showing a green icon? or do you think it should show the error icon indefinitely (until events are garbage collected)?

I tried the latest master which has your change but I didn't see any noticeable difference in the display. So I guess it's working as intended for the time being.

**Comment by floreks** [comment] 2016-11-30 10:47
All error/warning messages are shown on the pod list if there are any.

Events should not be the only indicator of the pod status. They are helpful in case pod is in pending state and there are some errors. We can then display error message and show what is wrong. Pod success/running state should be more important than warnings. I guess I haven't considered that in the code.

#1502 is nice. It considers more fail cases.

**Comment by IanLewis** [comment] 2016-11-30 10:51
@floreks Yes exactly. I still think we should show event info we just need to use something else as the primary way to determine current status.

**Comment by IanLewis** [comment] 2017-01-20 05:43
#1502 is merged so closing

**Closed by IanLewis** 2017-01-20 05:43 UTC
Labels: area/dev, kind/bug, priority/P1
