### ISSUE TITLE
Logs cannot be viewed due out of memory error

### ISSUE THREAD

**Issue by clbsandroiddev** [kubernetes/dashboard#1834] opened 2017-04-07 12:21 UTC
#### Issue details
I just click "Logs" menu on the right of pods list and I got clash
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'EOF'
Trying to reach: 'http://10.48.6.73:9090/api/v1/pod/default/bcc-uaa-3853094751-3erhs/log'
```

##### Expected result
Show log console of pod

**Comment by maciaszczykm** [comment] 2017-04-07 13:04
Please provide us more details how to reproduce the issue, i.e. pod spec, logs from `kubectl` etc.

**Comment by clbsandroiddev** [comment] 2017-04-11 05:08
I think I found the cause of this crash
it seems like I made infinity loop and logs size is exceed the limit.
Then the view crash

**Steps to reproduce**
1. make while loop which print some message
2. try to click "Logs" menu on pods list

but if you give it some time. it will be resolved
Kubernetes version 1.5.4

**Comment by maciaszczykm** [comment] 2017-04-12 06:33
@clbsandroiddev Can you send us your pod/depolyment spec?

**Comment by gatoruso** [comment] 2017-04-13 23:32
I have been able to reproduce this scenario by viewing a large log--in my case, I use the apiserver log. The dashboard container is killed each time I attempt to view the log: `Reason:		OOMKilled`

The dashboard container has a memory resource limit of 50mb defined. Once I increase this limit sufficiently, I can no longer reproduce the issue.

The resource limit is defined because I deploy the dashboard Pod using the in-kubernetes-tree spec: https://github.com/kubernetes/kubernetes/blob/release-1.4/cluster/addons/dashboard/dashboard-controller.yaml. It's worth noting that the in-dashboard-tree Deployment spec does _not_ define resource limits . For an example, see https://github.com/kubernetes/dashboard/blob/v1.4.2/src/deploy/kubernetes-dashboard.yaml.

@clbsandroiddev Does your dashboard Deployment spec define a memory resource limit?

(I have not yet tried to find a root cause for the issue, but I suppose the dashboard backend might be reading the entirety of the log into memory before returning some portion of it to the dashboard client.)

**Comment by floreks** [comment] 2017-04-14 10:59
Our main problem is that on logs page load [full app log is loaded](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/logs/stateconfig.js#L61) even so only part of it is displayed. On subsequent calls when you use paging controls to "scroll" logs only [part which should be displayed is loaded](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/logs/controller.js#L142). We should take care of that first. 

As for the `OOMKilled` crash it can happen not only with big logs but also when you have cluster with 500-1000+ pods. Backend will always have to load all the information because kubernetes itself does not support paging. I'd advise increasing memory limits in such cases to make sure that it won't crash.

**Comment by maciaszczykm** [comment] 2017-04-18 09:12
Added it as an action item for the future.

> but if you give it some time. it will be resolved

@clbsandroiddev We are grateful for any contributions.

**Comment by cheld** [comment] 2017-04-25 08:53
I have a look

**Comment by cheld** [comment] 2017-04-25 08:57
I had a quick look into the documentation: 

https://kubernetes.io/docs/concepts/cluster-administration/logging/

Normal pods have a log-retention of 10MB. System pods e.g. apiserver have a log-retention of 100 MB.

So, the 50mb memory limit of Dashboard was certainly not enough with the current implementation to handle maximum apiserver logs.

**Comment by cheld** [comment] 2017-04-25 09:44
This seems to be the place logs are loaded from disc by kubelet
https://github.com/kubernetes/kubernetes/blob/1cf6ef08df6deade958d0e6468474faea3ae4799/pkg/kubelet/kuberuntime/kuberuntime_logs.go#L121

**Comment by bcorijn** [comment] 2017-04-26 09:11
Just hit this as well after turning on `--log-queries` on the dnsmasq container in kube-dns pods, while trying to chase some DNS issues. Should be an easy change to reproduce.

**Comment by maciaszczykm** [comment] 2017-05-09 07:39
> So, the 50mb memory limit of Dashboard was certainly not enough with the current implementation to handle maximum apiserver logs.

Closed in https://github.com/kubernetes/kubernetes/pull/44712.

**Comment by cheld** [comment] 2017-05-23 14:06
I created a couple of manifest files that create log messages in docs/testing. 

After creating 100mb of logs Dashboard gets slow. I have not checked, but I a assume that Linux starts swapping if the memory limit is exceeded. In the cloud swapping is turned of and I assume Dashboard will become slow.

In any case, it should be improved.

The easiest solution seems to show only the last 10 or 100 pages and show a warning if data is cut. In addition we could provide download link for full log.

The api is not really prepared to do paging. Still, it could be possible combining a couple of options, like byte-limit. But it is more effort.

**Comment by cheld** [comment] 2017-05-24 08:59
I will try to twist the api to create kind of a paging on the apiserver.

**Closed** 2017-06-19 12:43 UTC
Labels: kind/bug, priority/P1
