### ISSUE TITLE
Memory usage chart flickers in chrome and CPU usage chart flickers in Microsoft Edge

### ISSUE THREAD

**Issue by kyandaks** [kubernetes/dashboard#7635] opened 2023-02-28 13:36 UTC
### What happened?

While viewing the pod list view and pod detail view pages, the memory usage chart keeps on flickering in Google chrome while CPU usage keeps flickering in Microsoft edge
I have attached the screenshot below:
![memory-usage-flickers](https://user-images.githubusercontent.com/45067380/221867100-048c6eeb-49b7-4aec-bcf5-87f32f7a600d.jpg)

### What did you expect to happen?

The memory usage chart and CPU usage chart should not flicker as in the screenshot attached
![memory-usage-stable](https://user-images.githubusercontent.com/45067380/221867597-c07d2701-0967-4359-a3bc-a737644ee0ed.png)

### How can we reproduce it (as minimally and precisely as possible)?

You can try accessing Kubernetes dashboard in Google chrome and Microsoft edge browsers

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Kubernetes Dashboard version

v2.5.1

### Kubernetes version

v1.23

**Comment by floreks** [comment] 2023-03-01 09:38
Duplicate of https://github.com/kubernetes/dashboard/issues/5102

/close

**Closed by floreks** 2023-03-01 09:38 UTC
Labels: kind/bug
