### ISSUE TITLE
Resource count listed but no resources in the list

### ISSUE THREAD

**Issue by andysworkshop** [kubernetes/dashboard#7548] opened 2022-11-30 18:00 UTC
### What happened?

I installed the dashboard into a GKE cluster with [OIDC enabled](https://cloud.google.com/kubernetes-engine/docs/how-to/oidc) and Istio used as a service mesh. Istio manages ingress and ensures that a valid `Authorization` header is present upon entry into the cluster. Auto-mTLS is enabled throughout and dashboard is configured for plain http with Istio managing the security. There are no Istio-related problems accessing the dashboard. That part is all good.

However when I login to the dashboard and select a namespace where I have access to resources I get this view for every type of resource: pods, deployments, configMaps etc. etc. The resource count is correctly displayed but there is nothing in the resource list:

![image](https://user-images.githubusercontent.com/4107468/204869365-d138a6d6-5003-4fc2-a114-03495b172604.png)

### What did you expect to happen?

Authorized resources should be listed.

### How can we reproduce it (as minimally and precisely as possible)?

I'm not sure that you'd want to reproduce this yourself?

### Anything else we need to know?

* There are no errors in the dashboard pod logs
* There are no errors in the networking or console browser dev tools
* kubectl access into the cluster with this same OIDC login works fine: pods etc. are all accessible and can be shell'd into, logs inspected, yaml retrieved etc.
* The dashboard was installed from the helm chart with `rbac.create=true`. 
* I have overridden `KUBERNETES_SERVICE_HOST` in the pod to be the IP address of the anthos envoy proxy service that you must use as the API server address in GKE for OIDC tokens to be evaluated for rbac. The default entry point will not recognise them. This seems to work OK. I did try `--apiserver-host` first with a cluster-internal service address of the envoy proxy and whilst this was detected by dashboard it resulted in a startup failure regarding the API server signing CA certificate being unknown to dashboard so obviously `--apiserver-host` switches out more than just the default IP address because the envoy proxy cert and the default API server cert are both issued by the same cluster CA. Anyway, overriding `KUBERNETES_SERVICE_HOST` seemed to solve that startup issue though I am concerned that I've trigged unintended consequences.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

v1.24.4

### Dev environment

not applicable

**Comment by andysworkshop** [comment] 2022-12-01 09:05
I will also add that I can see all the successful API server calls from dashboard in the GKE anthos envoy API proxy logs, e.g:
```
[2022-12-01T09:01:10.940Z] "GET /api/v1/namespaces/myns/pods HTTP/1.1" 200 - 0 33501 [etc...]
[2022-12-01T09:01:37.940Z] "GET /api/v1/namespaces/myns/services HTTP/1.1" 200 - 0 32625 [etc...]
```

**Comment by floreks** [comment] 2022-12-02 09:35
Duplicate of https://github.com/kubernetes/dashboard/issues/6637

/close

**Closed by floreks** 2022-12-02 09:35 UTC
Labels: kind/bug

**Comment by andysworkshop** [comment] 2022-12-02 19:09
I will also add that I can see all the successful API server calls from dashboard in the GKE anthos envoy API proxy logs, e.g:
```
[2022-12-01T09:01:10.940Z] "GET /api/v1/namespaces/myns/pods HTTP/1.1" 200 - 0 33501 [etc...]
[2022-12-01T09:01:37.940Z] "GET /api/v1/namespaces/myns/services HTTP/1.1" 200 - 0 32625 [etc...]
```

> @floreks: Closing this issue.

Yes that fixed it. Thanks.
