### ISSUE TITLE
Allow application deep linking by using History.pushState() instead of URL hash

### ISSUE THREAD

**Issue by greggbjensen** [kubernetes/dashboard#5775] opened 2021-01-27 22:38 UTC
##### What would you like to be added
We launch the Kubernetes Dashboard for our developers through command script.  We generally want them to go to a specific area and namespace after sign in.  Because the area and namespace is part of the hash in the URL, this is ignored by the command line and most authentication redirects.  This means we cannot link directly to anywhere but the default page, which slows down development.

![image](https://user-images.githubusercontent.com/1800213/106063196-0be77f80-60b5-11eb-9579-e75f22666f42.png)

##### Why is this needed

Removing the URL hash, and directly supporting pushState, will allow command script and other applications to link directly to a specific area and namespace of the Kubernetes Dashboard after sign-in redirect.

##### Comments
This feature would greatly speed up the development and ease of use of the Kubernetes Dashboard for teams by allowing cross-linking.

**Comment by greggbjensen** [comment] 2021-01-27 22:39
This is also related to #5340.

**Comment by floreks** [comment] 2021-01-28 11:04
This is a direct duplicate of #5340. We already have a history service. I'll add the support today for preserving deep-links after being redirected to the login view. Closing this as we already have the same issue.

/close

**Closed** 2021-01-28 11:04 UTC
Labels: kind/feature

**Comment by floreks** [comment] 2021-01-28 11:20
Related PR: https://github.com/kubernetes/dashboard/pull/5777
