### ISSUE TITLE
helm chart version 7.0.3 not available anymore

### ISSUE THREAD

**Issue by pandorasNox** [kubernetes/dashboard#8200] opened 2023-08-21 09:17 UTC
### What happened?

just last week we still could install the k8s-dashboard helm chart in version 7.0.3

this week it is not possible anymore -> the only available version now is: 7.0.0-alpha0

could this be related to: https://github.com/kubernetes/dashboard/commit/c51361ae440860e957e60ec0fa005b00c2de5150
?

this breaks our cluster updates atm

### What did you expect to happen?

installing the helm chart in version 7.0.3 works

### How can we reproduce it (as minimally and precisely as possible)?

`helm repo add dashboard https://kubernetes.github.io/dashboard/`

`helm fetch dashboard/kubernetes-dashboard --untar -d /tmp/kubernetes-dashboard/dashboard --version 7.0.3`

this yields:

> Error: chart "kubernetes-dashboard" matching 7.0.3 not found in dashboard index. (try 'helm repo update'): no chart version found for kubernetes-dashboard-7.0.3

also see:
`helm search repo dashboard/kubernetes-dashboard --versions`

this yields (at the time of writing):
```
NAME                          	CHART VERSION	APP VERSION	DESCRIPTION
dashboard/kubernetes-dashboard	6.0.8        	v2.7.0     	General-purpose web UI for Kubernetes clusters
dashboard/kubernetes-dashboard	6.0.7        	v2.7.0     	General-purpose web UI for Kubernetes clusters
dashboard/kubernetes-dashboard	6.0.6        	v2.7.0     	General-purpose web UI for Kubernetes clusters
dashboard/kubernetes-dashboard	6.0.5        	v2.7.0     	General-purpose web UI for Kubernetes clusters
dashboard/kubernetes-dashboard	6.0.0        	2.7.0      	General-purpose web UI for Kubernetes clusters
dashboard/kubernetes-dashboard	5.11.0       	2.7.0      	General-purpose web UI for Kubernetes clusters
[...]
```

### What browsers are you seeing the problem on?

- not browser related

### Kubernetes Dashboard version

- not relevant (the chart version is relevant: 7.0.3)

### Kubernetes version

- not relevant

**Comment by maciaszczykm** [comment] 2023-08-21 10:06
Can you switch to https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard/7.0.0-alpha0? We had to remove 7.0.3 due to versioning error on our side.

**Comment by floreks** [comment] 2023-08-21 12:11
Duplicate of https://github.com/kubernetes/dashboard/issues/8191

We have "rereleased" v7 and marked it as alpha since the app version is also an alpha.

/close

**Closed by floreks** 2023-08-21 12:11 UTC
Labels: kind/bug
