### ISSUE TITLE
Replace internalclientset to client-go

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/dashboard#1631] opened 2017-02-13 07:05 UTC
Currently the backend of UI is still using internalclientset. Since most of kubernetes code is changing to use client-go, it may be necessary to use client-go in dashboard backend also.

**Comment by maciaszczykm** [comment] 2017-02-16 12:45
Closing as duplicate of #1457.

**Closed by maciaszczykm** 2017-02-16 12:45 UTC
Labels: area/api, kind/refactoring, priority/P1
