### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by CooCoode** [kubernetes/dashboard#1823] opened 2017-04-06 09:53 UTC
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list daemonsets.extensions in the namespace "default". (get daemonsets.extensions)
```

**Comment by maciaszczykm** [comment] 2017-04-06 09:56
Duplicate of #1803.

**Closed by maciaszczykm** 2017-04-06 09:56 UTC

**Comment by CooCoode** [comment] 2017-04-06 09:58
@maciaszczykm thank you
